import { execFile } from "node:child_process";
import { access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { promisify } from "node:util";

import type {
  AliasDeclaration,
  CodegenDocument,
  Declaration,
  EnumDeclaration,
  StructDeclaration,
  StructField,
  TypeExpression,
  UnionDeclaration,
} from "./core.ts";

const execFileAsync = promisify(execFile);
const generatedFileHeader =
  "// Code generated by scripts/schema-to-code.ts. DO NOT EDIT.";

interface SerdeDirections {
  deserialize: boolean;
  serialize: boolean;
}

export function renderRustDocument(document: CodegenDocument): string {
  const { declarations, directions } = selectRustDeclarations(document);
  const needsValueImport = declarations.some(declarationUsesJsonValue);
  const needsMapImport = declarations.some(declarationUsesMap);
  const attributes = [
    "#![allow(dead_code)]",
    "#![allow(clippy::enum_variant_names)]",
    "#![allow(clippy::struct_field_names)]",
    "#![allow(clippy::doc_markdown)]",
    "#![allow(clippy::doc_broken_link)]",
    "#![allow(clippy::doc_lazy_continuation)]",
    "#![allow(clippy::doc_link_with_quotes)]",
    "#![allow(clippy::too_many_lines)]",
    "#![allow(clippy::upper_case_acronyms)]",
    "#![allow(clippy::use_self)]",
  ];
  const serdeImports = [
    ...(Array.from(directions.values()).some((value) => value.deserialize)
      ? ["Deserialize"]
      : []),
    ...(Array.from(directions.values()).some((value) => value.serialize)
      ? ["Serialize"]
      : []),
  ];
  const imports = [`use serde::{${serdeImports.join(", ")}};`];
  if (needsValueImport) {
    imports.push("use serde_json::Value;");
  }
  if (needsMapImport) {
    imports.push("use std::collections::HashMap;");
  }

  const parts: string[] = [
    generatedFileHeader,
    attributes.join("\n"),
    imports.join("\n"),
  ];
  for (const declaration of declarations) {
    parts.push(
      renderRustDeclaration(
        declaration,
        directions.get(declaration.name) ??
          fail(`Missing serde directions for ${declaration.name}`),
      ),
    );
  }
  return `${parts.join("\n\n")}\n`;
}

export async function formatRustOutput(outputPath: string): Promise<void> {
  const manifestPath = await findNearestCargoManifest(outputPath);
  await execFileAsync(
    "cargo",
    ["+nightly", "fmt", "--manifest-path", manifestPath],
    {
      cwd: dirname(manifestPath),
    },
  );
}

function renderRustDeclaration(
  declaration: Declaration,
  directions: SerdeDirections,
): string {
  switch (declaration.kind) {
    case "alias":
      return renderRustAlias(declaration);
    case "enum":
      return renderRustEnum(declaration, directions);
    case "struct":
      return renderRustStruct(declaration, directions);
    case "union":
      return renderRustUnion(declaration, directions);
  }
}

function renderRustAlias(declaration: AliasDeclaration): string {
  const comments = renderRustComment(declaration.description);
  const body = `pub type ${declaration.name} = ${renderRustType(declaration.target, false, false)};`;
  return comments ? `${comments}\n${body}` : body;
}

function renderRustEnum(
  declaration: EnumDeclaration,
  directions: SerdeDirections,
): string {
  if (declaration.primitive !== "string") {
    throw new Error(
      `Rust enum ${declaration.name} uses unsupported primitive ${declaration.primitive}`,
    );
  }

  const lines: string[] = [];
  const comments = renderRustComment(declaration.description);
  if (comments) {
    lines.push(comments);
  }
  lines.push(renderSerdeDerive(directions));
  lines.push("#[non_exhaustive]");
  lines.push(`pub enum ${declaration.name} {`);
  for (const variant of declaration.variants) {
    lines.push(`    #[serde(rename = ${JSON.stringify(variant.value)})]`);
    lines.push(`    ${variant.name},`);
  }
  if (directions.deserialize) {
    lines.push("    #[serde(other)]");
  }
  if (directions.serialize) {
    lines.push("    #[serde(skip_serializing)]");
  }
  lines.push("    Unknown,");
  lines.push("}");
  return lines.join("\n");
}

function renderRustStruct(
  declaration: StructDeclaration,
  directions: SerdeDirections,
): string {
  const lines: string[] = [];
  const comments = renderRustComment(declaration.description);
  if (comments) {
    lines.push(comments);
  }
  const derives = serdeDerives(directions);
  if (
    declaration.fields.every(
      (field) => field.kind === "property" && !field.required,
    )
  ) {
    derives.push("Default");
  }
  lines.push(`#[derive(${derives.join(", ")})]`);
  lines.push(`pub struct ${declaration.name} {`);
  for (const field of declaration.fields) {
    lines.push(
      ...renderRustStructField(field, declaration.name, directions.serialize),
    );
  }
  lines.push("}");
  return lines.join("\n");
}

function renderRustStructField(
  field: StructField,
  ownerName: string,
  serializable: boolean,
): string[] {
  if (field.kind === "flatten") {
    return [
      "    #[serde(flatten)]",
      `    pub ${field.name}: ${field.typeName},`,
    ];
  }

  const lines: string[] = [];
  const comments = renderRustComment(field.description, "    ");
  if (comments) {
    lines.push(comments);
  }
  const attributes: string[] = [];
  if (field.originalName !== normalizeRustFieldName(field.name)) {
    attributes.push(`rename = ${JSON.stringify(field.originalName)}`);
  }
  if (serializable && !field.required) {
    attributes.push('skip_serializing_if = "Option::is_none"');
  }
  if (attributes.length > 0) {
    lines.push(`    #[serde(${attributes.join(", ")})]`);
  }
  lines.push(
    `    pub ${field.name}: ${renderRustType(field.type, field.required, field.nullable, ownerName)},`,
  );
  return lines;
}

function renderRustUnion(
  declaration: UnionDeclaration,
  directions: SerdeDirections,
): string {
  const lines: string[] = [];
  const comments = renderRustComment(declaration.description);
  if (comments) {
    lines.push(comments);
  }
  const usesCustomDeserialize =
    declaration.representation === "untagged" &&
    declaration.untaggedDeserializeStrategy === "custom";
  const deriveDirections = {
    deserialize: directions.deserialize && !usesCustomDeserialize,
    serialize: directions.serialize,
  };
  const hasDerivedSerde =
    deriveDirections.deserialize || deriveDirections.serialize;
  if (hasDerivedSerde) {
    lines.push(renderSerdeDerive(deriveDirections));
  }
  lines.push("#[non_exhaustive]");
  if (hasDerivedSerde && declaration.representation === "tagged") {
    lines.push(
      `#[serde(tag = ${JSON.stringify(
        declaration.discriminator ??
          fail(`Missing discriminator for ${declaration.name}`),
      )})]`,
    );
  } else if (hasDerivedSerde) {
    lines.push("#[serde(untagged)]");
  }
  lines.push(`pub enum ${declaration.name} {`);
  for (const variant of declaration.variants) {
    if (hasDerivedSerde && declaration.representation === "tagged") {
      lines.push(
        `    #[serde(rename = ${JSON.stringify(
          variant.discriminatorValue ??
            fail(`Missing variant discriminator for ${declaration.name}`),
        )})]`,
      );
    }
    lines.push(`    ${variant.name}(${variant.typeName}),`);
  }
  if (declaration.representation === "tagged") {
    if (directions.deserialize) {
      lines.push("    #[serde(other)]");
    }
    if (directions.serialize) {
      lines.push("    #[serde(skip_serializing)]");
    }
    lines.push("    Unknown,");
  } else {
    lines.push("    #[allow(dead_code)]");
    if (directions.serialize) {
      lines.push("    #[serde(skip_serializing)]");
    }
    lines.push("    Unknown(Value),");
  }
  lines.push("}");
  return lines.join("\n");
}

function renderSerdeDerive(directions: SerdeDirections): string {
  return `#[derive(${serdeDerives(directions).join(", ")})]`;
}

function serdeDerives(directions: SerdeDirections): string[] {
  return [
    ...(directions.serialize ? ["Serialize"] : []),
    ...(directions.deserialize ? ["Deserialize"] : []),
  ];
}

function selectRustDeclarations(document: CodegenDocument): {
  declarations: Declaration[];
  directions: Map<string, SerdeDirections>;
} {
  if (!document.rustSerde) {
    return {
      declarations: document.declarations,
      directions: new Map(
        document.declarations.map((declaration) => [
          declaration.name,
          { deserialize: true, serialize: true },
        ]),
      ),
    };
  }

  const declarationsByName = new Map(
    document.declarations.map((declaration) => [declaration.name, declaration]),
  );
  const directions = new Map<string, SerdeDirections>();

  const visit = (name: string, direction: keyof SerdeDirections): void => {
    const declaration =
      declarationsByName.get(name) ?? fail(`Unknown Rust serde root ${name}`);
    const current = directions.get(name) ?? {
      deserialize: false,
      serialize: false,
    };
    if (current[direction]) {
      return;
    }
    directions.set(name, { ...current, [direction]: true });
    for (const dependency of declarationDependencies(declaration)) {
      visit(dependency, direction);
    }
  };

  for (const root of document.rustSerde.serialize ?? []) {
    visit(root, "serialize");
  }
  for (const root of document.rustSerde.deserialize ?? []) {
    visit(root, "deserialize");
  }

  return {
    declarations: document.declarations.filter((declaration) =>
      directions.has(declaration.name),
    ),
    directions,
  };
}

function declarationDependencies(declaration: Declaration): string[] {
  switch (declaration.kind) {
    case "alias":
      return typeDependencies(declaration.target);
    case "enum":
      return [];
    case "struct":
      return declaration.fields.flatMap((field) =>
        field.kind === "flatten"
          ? [field.typeName]
          : typeDependencies(field.type),
      );
    case "union":
      return declaration.variants.map((variant) => variant.typeName);
  }
}

function typeDependencies(type: TypeExpression): string[] {
  switch (type.kind) {
    case "named":
      return [type.name];
    case "array":
    case "optional":
      return typeDependencies(type.item);
    case "map":
      return type.value ? typeDependencies(type.value) : [];
    case "json_value":
    case "primitive":
      return [];
  }
}

function declarationUsesJsonValue(declaration: Declaration): boolean {
  if (
    declaration.kind === "union" &&
    declaration.representation === "untagged"
  ) {
    return true;
  }
  return declarationUsesType(declaration, "json_value");
}

function declarationUsesMap(declaration: Declaration): boolean {
  return declarationUsesType(declaration, "map");
}

function declarationUsesType(
  declaration: Declaration,
  kind: "json_value" | "map",
): boolean {
  switch (declaration.kind) {
    case "alias":
      return typeUsesKind(declaration.target, kind);
    case "enum":
    case "union":
      return false;
    case "struct":
      return declaration.fields.some(
        (field) => field.kind === "property" && typeUsesKind(field.type, kind),
      );
  }
}

function typeUsesKind(
  type: TypeExpression,
  kind: "json_value" | "map",
): boolean {
  if (type.kind === kind) {
    return true;
  }
  switch (type.kind) {
    case "array":
    case "optional":
      return typeUsesKind(type.item, kind);
    case "map":
      return type.value ? typeUsesKind(type.value, kind) : false;
    case "json_value":
    case "named":
    case "primitive":
      return false;
  }
}

function renderRustType(
  type: TypeExpression,
  required: boolean,
  nullable: boolean,
  recursiveOwner?: string,
): string {
  const baseType = (() => {
    switch (type.kind) {
      case "primitive":
        return renderRustPrimitive(type.primitive);
      case "named":
        return type.name === recursiveOwner ? `Box<${type.name}>` : type.name;
      case "array":
        return `Vec<${renderRustType(type.item, true, false)}>`;
      case "map":
        return `HashMap<String, ${type.value ? renderRustType(type.value, true, false) : fail("Map value type is required")}>`;
      case "json_value":
        return "Value";
      case "optional":
        return `Option<${renderRustType(type.item, true, false, recursiveOwner)}>`;
      default:
        return fail(
          `Unsupported Rust type expression: ${JSON.stringify(type)}`,
        );
    }
  })();

  if (!required || nullable) {
    return `Option<${baseType}>`;
  }
  return baseType;
}

function renderRustPrimitive(
  primitive: "string" | "boolean" | "integer" | "number",
): string {
  switch (primitive) {
    case "string":
      return "String";
    case "boolean":
      return "bool";
    case "integer":
      return "i64";
    case "number":
      return "f64";
    default:
      return fail(`Unsupported Rust primitive: ${primitive}`);
  }
}

function renderRustComment(
  description: string | undefined,
  indent = "",
): string | undefined {
  if (!description) {
    return undefined;
  }
  return description
    .split("\n")
    .map((line) => `${indent}///${line.length > 0 ? ` ${line}` : ""}`)
    .join("\n");
}

function normalizeRustFieldName(fieldName: string): string {
  return fieldName.startsWith("r#") ? fieldName.slice(2) : fieldName;
}

async function findNearestCargoManifest(startPath: string): Promise<string> {
  let currentDir = dirname(resolve(startPath));
  while (true) {
    const manifestPath = join(currentDir, "Cargo.toml");
    try {
      await access(manifestPath);
      return manifestPath;
    } catch {
      const parentDir = dirname(currentDir);
      if (parentDir === currentDir) {
        throw new Error(`Could not find Cargo.toml for ${startPath}`);
      }
      currentDir = parentDir;
    }
  }
}

function fail(message: string): never {
  throw new Error(message);
}
