[package]
edition = "2021"
name = "llm-agent"
version = "0.1.0"

[lints.clippy]
missing_errors_doc = "allow"
pedantic = "warn"
use_self = "warn"

[dependencies]
anyhow = "1.0.95"
async-stream = "0.3.6"
futures = "0.3.31"
futures-core = "0.3.31"
llm-sdk = { version = "0.1.0", path = "../sdk-rust" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.11"
tokio = { version = "1.42.0", features = ["full"] }

[dev-dependencies]
chrono = "0.4"
dotenvy = { version = "0.15.7" }
tokio = { version = "1.42.0", features = ["full"] }
