[package]
description = "Agents enable the development of agentic AI applications that can generate responses and execute tasks autonomously. Agents utilize the LLM SDK to interact with different language models and allow definitions of instructions, tools, and other language model parameters."
edition = "2021"
homepage = "https://llm-sdk.hoangvvo.com/"
license = "MIT"
name = "llm-agent"
readme = "README.md"
repository = "https://github.com/hoangvvo/llm-sdk"
version = "0.1.0"

[lints.clippy]
missing_errors_doc = "allow"
pedantic = "warn"
use_self = "warn"

[dependencies]
anyhow = "1.0.95"
async-stream = "0.3.6"
async-trait = "0.1.86"
futures = "0.3.31"
llm-sdk = { version = "0.1.0", path = "../sdk-rust" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.11"

[dev-dependencies]
axum = "0.8.1"
chrono = "0.4"
dotenvy = { version = "0.15.7" }
rand = { version = "0.8" }
reqwest = { version = "0.12.9", features = ["json"] }
schemars = "1.0.4"
similar = "2"
tokio = { version = "1.42.0", features = ["full"] }
tower = "0.5.1"
tower-http = { version = "0.6.2", features = ["cors"] }
urlencoding = "2.1.3"
