[package]
edition = "2021"
name = "llm_sdk"
version = "0.1.0"

[dependencies]
async-trait = "0.1.86"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
