[package]
edition = "2021"
name = "llm_sdk"
version = "0.1.0"

[dependencies]
async-trait = "0.1.86"
reqwest = { version = "0.12.12", features = ["json", "gzip", "stream"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.11"
tokio = { version = "1.42.0", features = ["full"] }
