[package]
edition = "2021"
name = "llm-sdk"
version = "0.1.0"

[lints.clippy]
pedantic = "warn"
use_self = "warn"

[dependencies]
async-stream = "0.3.6"
async-trait = "0.1.86"
base64 = "0.22.1"
eventsource-stream = "0.2.3"
futures = "0.3.31"
futures-core = "0.3.31"
reqwest = { version = "0.12.12", features = ["json", "gzip", "stream"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "2.0.11"

[dev-dependencies]
dotenvy = { version = "0.15.7" }
rodio = "0.17"
tokio = { version = "1.42.0", features = ["full"] }
