package openaichatapi

import (
	"encoding/json"
	"errors"
)

type CreateChatCompletionRequestAllOf2 struct {
	// Parameters for audio output. Required when audio output is requested with
	// `modalities: ["audio"]`. [Learn more](/docs/guides/audio).
	//
	Audio *CreateChatCompletionRequestAllOf2Audio `json:"audio,omitempty"`
	// Number between -2.0 and 2.0. Positive values penalize new tokens based on
	// their existing frequency in the text so far, decreasing the model's
	// likelihood to repeat the same line verbatim.
	//
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty"`
	// Deprecated in favor of `tool_choice`.
	//
	// Controls which (if any) function is called by the model.
	//
	// `none` means the model will not call a function and instead generates a
	// message.
	//
	// `auto` means the model can pick between generating a message or calling a
	// function.
	//
	// Specifying a particular function via `{"name": "my_function"}` forces the
	// model to call that function.
	//
	// `none` is the default when no functions are present. `auto` is the default
	// if functions are present.
	//
	FunctionCall *CreateChatCompletionRequestAllOf2FunctionCall `json:"function_call,omitempty"`
	// Deprecated in favor of `tools`.
	//
	// A list of functions the model may generate JSON inputs for.
	//
	Functions []ChatCompletionFunctions `json:"functions,omitempty"`
	// Modify the likelihood of specified tokens appearing in the completion.
	//
	// Accepts a JSON object that maps tokens (specified by their token ID in the
	// tokenizer) to an associated bias value from -100 to 100. Mathematically,
	// the bias is added to the logits generated by the model prior to sampling.
	// The exact effect will vary per model, but values between -1 and 1 should
	// decrease or increase likelihood of selection; values like -100 or 100
	// should result in a ban or exclusive selection of the relevant token.
	//
	LogitBias map[string]int `json:"logit_bias,omitempty"`
	// Whether to return log probabilities of the output tokens or not. If true,
	// returns the log probabilities of each output token returned in the
	// `content` of `message`.
	//
	Logprobs *bool `json:"logprobs,omitempty"`
	// An upper bound for the number of tokens that can be generated for a completion, including visible output tokens and [reasoning tokens](/docs/guides/reasoning).
	//
	MaxCompletionTokens *int `json:"max_completion_tokens,omitempty"`
	// The maximum number of [tokens](/tokenizer) that can be generated in the
	// chat completion. This value can be used to control
	// [costs](https://openai.com/api/pricing/) for text generated via API.
	//
	// This value is now deprecated in favor of `max_completion_tokens`, and is
	// not compatible with [o-series models](/docs/guides/reasoning).
	//
	MaxTokens *int `json:"max_tokens,omitempty"`
	// A list of messages comprising the conversation so far. Depending on the
	// [model](/docs/models) you use, different message types (modalities) are
	// supported, like [text](/docs/guides/text-generation),
	// [images](/docs/guides/vision), and [audio](/docs/guides/audio).
	//
	Messages   []ChatCompletionRequestMessage `json:"messages"`
	Modalities *ResponseModalities            `json:"modalities,omitempty"`
	// Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI
	// offers a wide range of models with different capabilities, performance
	// characteristics, and price points. Refer to the [model guide](/docs/models)
	// to browse and compare available models.
	//
	Model ModelIdsShared `json:"model"`
	// How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.
	N                 *int               `json:"n,omitempty"`
	ParallelToolCalls *ParallelToolCalls `json:"parallel_tool_calls,omitempty"`
	// Configuration for a [Predicted Output](/docs/guides/predicted-outputs),
	// which can greatly improve response times when large parts of the model
	// response are known ahead of time. This is most common when you are
	// regenerating a file with only minor changes to most of the content.
	//
	Prediction *CreateChatCompletionRequestAllOf2Prediction `json:"prediction,omitempty"`
	// Number between -2.0 and 2.0. Positive values penalize new tokens based on
	// whether they appear in the text so far, increasing the model's likelihood
	// to talk about new topics.
	//
	PresencePenalty *float64         `json:"presence_penalty,omitempty"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`
	// An object specifying the format that the model must output.
	//
	// Setting to `{ "type": "json_schema", "json_schema": {...} }` enables
	// Structured Outputs which ensures the model will match your supplied JSON
	// schema. Learn more in the [Structured Outputs
	// guide](/docs/guides/structured-outputs).
	//
	// Setting to `{ "type": "json_object" }` enables the older JSON mode, which
	// ensures the message the model generates is valid JSON. Using `json_schema`
	// is preferred for models that support it.
	//
	ResponseFormat *CreateChatCompletionRequestAllOf2ResponseFormat `json:"response_format,omitempty"`
	// This feature is in Beta.
	// If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.
	// Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
	//
	Seed *int               `json:"seed,omitempty"`
	Stop *StopConfiguration `json:"stop,omitempty"`
	// Whether or not to store the output of this chat completion request for
	// use in our [model distillation](/docs/guides/distillation) or
	// [evals](/docs/guides/evals) products.
	//
	// Supports text and image inputs. Note: image inputs over 8MB will be dropped.
	//
	Store *bool `json:"store,omitempty"`
	// If set to true, the model response data will be streamed to the client
	// as it is generated using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format).
	// See the [Streaming section below](/docs/api-reference/chat/streaming)
	// for more information, along with the [streaming responses](/docs/guides/streaming-responses)
	// guide for more information on how to handle the streaming events.
	//
	Stream        *bool                           `json:"stream,omitempty"`
	StreamOptions *ChatCompletionStreamOptions    `json:"stream_options,omitempty"`
	ToolChoice    *ChatCompletionToolChoiceOption `json:"tool_choice,omitempty"`
	// A list of tools the model may call. You can provide either
	// [custom tools](/docs/guides/function-calling#custom-tools) or
	// [function tools](/docs/guides/function-calling).
	//
	Tools []CreateChatCompletionRequestAllOf2ToolsItem `json:"tools,omitempty"`
	// An integer between 0 and 20 specifying the number of most likely tokens to
	// return at each token position, each with an associated log probability.
	// `logprobs` must be set to `true` if this parameter is used.
	//
	TopLogprobs *int       `json:"top_logprobs,omitempty"`
	Verbosity   *Verbosity `json:"verbosity,omitempty"`
	// This tool searches the web for relevant results to use in a response.
	// Learn more about the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
	//
	WebSearchOptions *CreateChatCompletionRequestAllOf2WebSearchOptions `json:"web_search_options,omitempty"`
}

// Parameters for audio output. Required when audio output is requested with
// `modalities: ["audio"]`. [Learn more](/docs/guides/audio).
type CreateChatCompletionRequestAllOf2Audio struct {
	// Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
	// `opus`, or `pcm16`.
	//
	Format CreateChatCompletionRequestAllOf2AudioFormat `json:"format"`
	// The voice the model uses to respond. Supported built-in voices are
	// `alloy`, `ash`, `ballad`, `coral`, `echo`, `fable`, `nova`, `onyx`,
	// `sage`, `shimmer`, `marin`, and `cedar`. You may also provide a
	// custom voice object with an `id`, for example `{ "id": "voice_1234" }`.
	//
	Voice VoiceIdsOrCustomVoice `json:"voice"`
}

// Specifies the output audio format. Must be one of `wav`, `mp3`, `flac`,
// `opus`, or `pcm16`.
type CreateChatCompletionRequestAllOf2AudioFormat string

const (
	CreateChatCompletionRequestAllOf2AudioFormatWav   CreateChatCompletionRequestAllOf2AudioFormat = "wav"
	CreateChatCompletionRequestAllOf2AudioFormatAac   CreateChatCompletionRequestAllOf2AudioFormat = "aac"
	CreateChatCompletionRequestAllOf2AudioFormatMp3   CreateChatCompletionRequestAllOf2AudioFormat = "mp3"
	CreateChatCompletionRequestAllOf2AudioFormatFlac  CreateChatCompletionRequestAllOf2AudioFormat = "flac"
	CreateChatCompletionRequestAllOf2AudioFormatOpus  CreateChatCompletionRequestAllOf2AudioFormat = "opus"
	CreateChatCompletionRequestAllOf2AudioFormatPcm16 CreateChatCompletionRequestAllOf2AudioFormat = "pcm16"
)

// `none` means the model will not call a function and instead generates a message. `auto` means the model can pick between generating a message or calling a function.
type CreateChatCompletionRequestAllOf2FunctionCallString *string

// Deprecated in favor of `tool_choice`.
//
// Controls which (if any) function is called by the model.
//
// `none` means the model will not call a function and instead generates a
// message.
//
// `auto` means the model can pick between generating a message or calling a
// function.
//
// Specifying a particular function via `{"name": "my_function"}` forces the
// model to call that function.
//
// `none` is the default when no functions are present. `auto` is the default
// if functions are present.
type CreateChatCompletionRequestAllOf2FunctionCall struct {
	CreateChatCompletionRequestAllOf2FunctionCallString *CreateChatCompletionRequestAllOf2FunctionCallString
	ChatCompletionFunctionCallOption                    *ChatCompletionFunctionCallOption
}

func (u *CreateChatCompletionRequestAllOf2FunctionCall) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.CreateChatCompletionRequestAllOf2FunctionCallString != nil {
		return json.Marshal(u.CreateChatCompletionRequestAllOf2FunctionCallString)
	}
	if u.ChatCompletionFunctionCallOption != nil {
		return json.Marshal(u.ChatCompletionFunctionCallOption)
	}
	return nil, errors.New("invalid CreateChatCompletionRequestAllOf2FunctionCall: all variants are nil")
}

func (u *CreateChatCompletionRequestAllOf2FunctionCall) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = CreateChatCompletionRequestAllOf2FunctionCall{}
	switch value := raw.(type) {
	case string:
		var v CreateChatCompletionRequestAllOf2FunctionCallString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.CreateChatCompletionRequestAllOf2FunctionCallString = &v
		return nil
	case map[string]interface{}:
		if value["name"] != nil {
			var v ChatCompletionFunctionCallOption
			if err := json.Unmarshal(data, &v); err != nil {
				return nil
			}
			u.ChatCompletionFunctionCallOption = &v
			return nil
		}
		return nil
	}
	return nil
}

// Configuration for a [Predicted Output](/docs/guides/predicted-outputs),
// which can greatly improve response times when large parts of the model
// response are known ahead of time. This is most common when you are
// regenerating a file with only minor changes to most of the content.
type CreateChatCompletionRequestAllOf2Prediction struct {
	Content *PredictionContent
}

func (u *CreateChatCompletionRequestAllOf2Prediction) MarshalJSON() ([]byte, error) {
	if u.Content != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*PredictionContent
		}{
			Type:              "content",
			PredictionContent: u.Content,
		})
	}
	return nil, errors.New("invalid CreateChatCompletionRequestAllOf2Prediction: all variants are nil")
}

func (u *CreateChatCompletionRequestAllOf2Prediction) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = CreateChatCompletionRequestAllOf2Prediction{}
	switch discriminator {
	case "content":
		var value PredictionContent
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Content = &value
	default:
		return nil
	}
	return nil
}

// An object specifying the format that the model must output.
//
// Setting to `{ "type": "json_schema", "json_schema": {...} }` enables
// Structured Outputs which ensures the model will match your supplied JSON
// schema. Learn more in the [Structured Outputs
// guide](/docs/guides/structured-outputs).
//
// Setting to `{ "type": "json_object" }` enables the older JSON mode, which
// ensures the message the model generates is valid JSON. Using `json_schema`
// is preferred for models that support it.
type CreateChatCompletionRequestAllOf2ResponseFormat struct {
	Text       *ResponseFormatText
	JsonSchema *ResponseFormatJsonSchema
	JsonObject *ResponseFormatJsonObject
}

func (u *CreateChatCompletionRequestAllOf2ResponseFormat) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ResponseFormatText
		}{
			Type:               "text",
			ResponseFormatText: u.Text,
		})
	}
	if u.JsonSchema != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ResponseFormatJsonSchema
		}{
			Type:                     "json_schema",
			ResponseFormatJsonSchema: u.JsonSchema,
		})
	}
	if u.JsonObject != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ResponseFormatJsonObject
		}{
			Type:                     "json_object",
			ResponseFormatJsonObject: u.JsonObject,
		})
	}
	return nil, errors.New("invalid CreateChatCompletionRequestAllOf2ResponseFormat: all variants are nil")
}

func (u *CreateChatCompletionRequestAllOf2ResponseFormat) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = CreateChatCompletionRequestAllOf2ResponseFormat{}
	switch discriminator {
	case "text":
		var value ResponseFormatText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	case "json_schema":
		var value ResponseFormatJsonSchema
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.JsonSchema = &value
	case "json_object":
		var value ResponseFormatJsonObject
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.JsonObject = &value
	default:
		return nil
	}
	return nil
}

type CreateChatCompletionRequestAllOf2ToolsItem struct {
	Function *ChatCompletionTool
	Custom   *CustomToolChatCompletions
}

func (u *CreateChatCompletionRequestAllOf2ToolsItem) MarshalJSON() ([]byte, error) {
	if u.Function != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionTool
		}{
			Type:               "function",
			ChatCompletionTool: u.Function,
		})
	}
	if u.Custom != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*CustomToolChatCompletions
		}{
			Type:                      "custom",
			CustomToolChatCompletions: u.Custom,
		})
	}
	return nil, errors.New("invalid CreateChatCompletionRequestAllOf2ToolsItem: all variants are nil")
}

func (u *CreateChatCompletionRequestAllOf2ToolsItem) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = CreateChatCompletionRequestAllOf2ToolsItem{}
	switch discriminator {
	case "function":
		var value ChatCompletionTool
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Function = &value
	case "custom":
		var value CustomToolChatCompletions
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Custom = &value
	default:
		return nil
	}
	return nil
}

// This tool searches the web for relevant results to use in a response.
// Learn more about the [web search tool](/docs/guides/tools-web-search?api-mode=chat).
type CreateChatCompletionRequestAllOf2WebSearchOptions struct {
	SearchContextSize *WebSearchContextSize `json:"search_context_size,omitempty"`
	// Approximate location parameters for the search.
	//
	UserLocation *CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocation `json:"user_location,omitempty"`
}

// Approximate location parameters for the search.
type CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocation struct {
	Approximate WebSearchLocation `json:"approximate"`
	// The type of location approximation. Always `approximate`.
	//
	Type CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocationType `json:"type"`
}

// The type of location approximation. Always `approximate`.
type CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocationType string

const (
	CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocationTypeApproximate CreateChatCompletionRequestAllOf2WebSearchOptionsUserLocationType = "approximate"
)

type CreateChatCompletionRequest struct {
	CreateModelResponseProperties
	CreateChatCompletionRequestAllOf2
}

// Represents a chat completion response returned by model, based on the provided input.
type CreateChatCompletionResponse struct {
	// A list of chat completion choices. Can be more than one if `n` is greater than 1.
	Choices []CreateChatCompletionResponseChoicesItem `json:"choices"`
	// The Unix timestamp (in seconds) of when the chat completion was created.
	Created int `json:"created"`
	// A unique identifier for the chat completion.
	Id string `json:"id"`
	// The model used for the chat completion.
	Model string `json:"model"`
	// The object type, which is always `chat.completion`.
	Object      CreateChatCompletionResponseObject `json:"object"`
	ServiceTier *ServiceTier                       `json:"service_tier,omitempty"`
	// This fingerprint represents the backend configuration that the model runs with.
	//
	// Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
	//
	SystemFingerprint *string          `json:"system_fingerprint,omitempty"`
	Usage             *CompletionUsage `json:"usage,omitempty"`
}

type CreateChatCompletionResponseChoicesItem struct {
	// The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
	// `length` if the maximum number of tokens specified in the request was reached,
	// `content_filter` if content was omitted due to a flag from our content filters,
	// `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
	//
	FinishReason *CreateChatCompletionResponseChoicesItemFinishReason `json:"finish_reason,omitempty"`
	// The index of the choice in the list of choices.
	Index int `json:"index"`
	// Log probability information for the choice.
	Logprobs *CreateChatCompletionResponseChoicesItemLogprobs `json:"logprobs"`
	Message  ChatCompletionResponseMessage                    `json:"message"`
}

// The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
// `length` if the maximum number of tokens specified in the request was reached,
// `content_filter` if content was omitted due to a flag from our content filters,
// `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
type CreateChatCompletionResponseChoicesItemFinishReason string

const (
	CreateChatCompletionResponseChoicesItemFinishReasonStop          CreateChatCompletionResponseChoicesItemFinishReason = "stop"
	CreateChatCompletionResponseChoicesItemFinishReasonLength        CreateChatCompletionResponseChoicesItemFinishReason = "length"
	CreateChatCompletionResponseChoicesItemFinishReasonToolCalls     CreateChatCompletionResponseChoicesItemFinishReason = "tool_calls"
	CreateChatCompletionResponseChoicesItemFinishReasonContentFilter CreateChatCompletionResponseChoicesItemFinishReason = "content_filter"
	CreateChatCompletionResponseChoicesItemFinishReasonFunctionCall  CreateChatCompletionResponseChoicesItemFinishReason = "function_call"
)

// Log probability information for the choice.
type CreateChatCompletionResponseChoicesItemLogprobs struct {
	// A list of message content tokens with log probability information.
	Content []ChatCompletionTokenLogprob `json:"content"`
	// A list of message refusal tokens with log probability information.
	Refusal []ChatCompletionTokenLogprob `json:"refusal"`
}

// The object type, which is always `chat.completion`.
type CreateChatCompletionResponseObject string

const (
	CreateChatCompletionResponseObjectChatCompletion CreateChatCompletionResponseObject = "chat.completion"
)

// Represents a streamed chunk of a chat completion response returned
// by the model, based on the provided input.
// [Learn more](/docs/guides/streaming-responses).
type CreateChatCompletionStreamResponse struct {
	// A list of chat completion choices. Can contain more than one elements if `n` is greater than 1. Can also be empty for the
	// last chunk if you set `stream_options: {"include_usage": true}`.
	//
	Choices []CreateChatCompletionStreamResponseChoicesItem `json:"choices,omitempty"`
	// The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
	Created int `json:"created"`
	// A unique identifier for the chat completion. Each chunk has the same ID.
	Id string `json:"id"`
	// The model to generate the completion.
	Model string `json:"model"`
	// The object type, which is always `chat.completion.chunk`.
	Object      CreateChatCompletionStreamResponseObject `json:"object"`
	ServiceTier *ServiceTier                             `json:"service_tier,omitempty"`
	// This fingerprint represents the backend configuration that the model runs with.
	// Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
	//
	SystemFingerprint *string `json:"system_fingerprint,omitempty"`
	// An optional field that will only be present when you set
	// `stream_options: {"include_usage": true}` in your request. When present, it
	// contains a null value **except for the last chunk** which contains the
	// token usage statistics for the entire request.
	//
	// **NOTE:** If the stream is interrupted or cancelled, you may not
	// receive the final usage chunk which contains the total token usage for
	// the request.
	//
	Usage *CompletionUsage `json:"usage,omitempty"`
}

type CreateChatCompletionStreamResponseChoicesItem struct {
	Delta ChatCompletionStreamResponseDelta `json:"delta"`
	// The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
	// `length` if the maximum number of tokens specified in the request was reached,
	// `content_filter` if content was omitted due to a flag from our content filters,
	// `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
	//
	FinishReason *CreateChatCompletionStreamResponseChoicesItemFinishReason `json:"finish_reason,omitempty"`
	// The index of the choice in the list of choices.
	Index int `json:"index"`
	// Log probability information for the choice.
	Logprobs *CreateChatCompletionStreamResponseChoicesItemLogprobs `json:"logprobs,omitempty"`
}

// The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
// `length` if the maximum number of tokens specified in the request was reached,
// `content_filter` if content was omitted due to a flag from our content filters,
// `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
type CreateChatCompletionStreamResponseChoicesItemFinishReason string

const (
	CreateChatCompletionStreamResponseChoicesItemFinishReasonStop          CreateChatCompletionStreamResponseChoicesItemFinishReason = "stop"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonLength        CreateChatCompletionStreamResponseChoicesItemFinishReason = "length"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonToolCalls     CreateChatCompletionStreamResponseChoicesItemFinishReason = "tool_calls"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonContentFilter CreateChatCompletionStreamResponseChoicesItemFinishReason = "content_filter"
	CreateChatCompletionStreamResponseChoicesItemFinishReasonFunctionCall  CreateChatCompletionStreamResponseChoicesItemFinishReason = "function_call"
)

// Log probability information for the choice.
type CreateChatCompletionStreamResponseChoicesItemLogprobs struct {
	// A list of message content tokens with log probability information.
	Content []ChatCompletionTokenLogprob `json:"content"`
	// A list of message refusal tokens with log probability information.
	Refusal []ChatCompletionTokenLogprob `json:"refusal"`
}

// The object type, which is always `chat.completion.chunk`.
type CreateChatCompletionStreamResponseObject string

const (
	CreateChatCompletionStreamResponseObjectChatCompletionChunk CreateChatCompletionStreamResponseObject = "chat.completion.chunk"
)

type CreateModelResponsePropertiesAllOf2 struct {
	// An integer between 0 and 20 specifying the number of most likely tokens to
	// return at each token position, each with an associated log probability.
	//
	TopLogprobs *int `json:"top_logprobs,omitempty"`
}

type CreateModelResponseProperties struct {
	ModelResponseProperties
	CreateModelResponsePropertiesAllOf2
}

// Custom voice reference.
type VoiceIdsOrCustomVoiceVariant2 struct {
	// The custom voice ID, e.g. `voice_1234`.
	Id string `json:"id"`
}

// A built-in voice name or a custom voice reference.
type VoiceIdsOrCustomVoice struct {
	VoiceIdsShared                *VoiceIdsShared
	VoiceIdsOrCustomVoiceVariant2 *VoiceIdsOrCustomVoiceVariant2
}

func (u *VoiceIdsOrCustomVoice) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.VoiceIdsShared != nil {
		return json.Marshal(u.VoiceIdsShared)
	}
	if u.VoiceIdsOrCustomVoiceVariant2 != nil {
		return json.Marshal(u.VoiceIdsOrCustomVoiceVariant2)
	}
	return nil, errors.New("invalid VoiceIdsOrCustomVoice: all variants are nil")
}

func (u *VoiceIdsOrCustomVoice) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = VoiceIdsOrCustomVoice{}
	switch value := raw.(type) {
	case string:
		var v VoiceIdsShared
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.VoiceIdsShared = &v
		return nil
	case map[string]interface{}:
		if value["id"] != nil {
			var v VoiceIdsOrCustomVoiceVariant2
			if err := json.Unmarshal(data, &v); err != nil {
				return nil
			}
			u.VoiceIdsOrCustomVoiceVariant2 = &v
			return nil
		}
		return nil
	}
	return nil
}

// Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
type ChatCompletionFunctionCallOption struct {
	// The name of the function to call.
	Name string `json:"name"`
}

type ChatCompletionFunctions struct {
	// A description of what the function does, used by the model to choose when and how to call the function.
	Description *string `json:"description,omitempty"`
	// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
	Name       string              `json:"name"`
	Parameters *FunctionParameters `json:"parameters,omitempty"`
}

type ChatCompletionRequestMessage struct {
	Developer *ChatCompletionRequestDeveloperMessage
	System    *ChatCompletionRequestSystemMessage
	User      *ChatCompletionRequestUserMessage
	Assistant *ChatCompletionRequestAssistantMessage
	Tool      *ChatCompletionRequestToolMessage
	Function  *ChatCompletionRequestFunctionMessage
}

func (u *ChatCompletionRequestMessage) MarshalJSON() ([]byte, error) {
	if u.Developer != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestDeveloperMessage
		}{
			Role:                                  "developer",
			ChatCompletionRequestDeveloperMessage: u.Developer,
		})
	}
	if u.System != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestSystemMessage
		}{
			Role:                               "system",
			ChatCompletionRequestSystemMessage: u.System,
		})
	}
	if u.User != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestUserMessage
		}{
			Role:                             "user",
			ChatCompletionRequestUserMessage: u.User,
		})
	}
	if u.Assistant != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestAssistantMessage
		}{
			Role:                                  "assistant",
			ChatCompletionRequestAssistantMessage: u.Assistant,
		})
	}
	if u.Tool != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestToolMessage
		}{
			Role:                             "tool",
			ChatCompletionRequestToolMessage: u.Tool,
		})
	}
	if u.Function != nil {
		return json.Marshal(struct {
			Role string `json:"role"`
			*ChatCompletionRequestFunctionMessage
		}{
			Role:                                 "function",
			ChatCompletionRequestFunctionMessage: u.Function,
		})
	}
	return nil, errors.New("invalid ChatCompletionRequestMessage: all variants are nil")
}

func (u *ChatCompletionRequestMessage) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawRole, ok := raw["role"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawRole, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionRequestMessage{}
	switch discriminator {
	case "developer":
		var value ChatCompletionRequestDeveloperMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Developer = &value
	case "system":
		var value ChatCompletionRequestSystemMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.System = &value
	case "user":
		var value ChatCompletionRequestUserMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.User = &value
	case "assistant":
		var value ChatCompletionRequestAssistantMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Assistant = &value
	case "tool":
		var value ChatCompletionRequestToolMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Tool = &value
	case "function":
		var value ChatCompletionRequestFunctionMessage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Function = &value
	default:
		return nil
	}
	return nil
}

type ResponseModalitiesItem string

const (
	ResponseModalitiesItemText  ResponseModalitiesItem = "text"
	ResponseModalitiesItemAudio ResponseModalitiesItem = "audio"
)

// Output types that you would like the model to generate.
// Most models are capable of generating text, which is the default:
//
// `["text"]`
//
// The `gpt-4o-audio-preview` model can also be used to
// [generate audio](/docs/guides/audio). To request that this model generate
// both text and audio responses, you can use:
//
// `["text", "audio"]`
type ResponseModalities []ResponseModalitiesItem

type ModelIdsShared *string

// Whether to enable [parallel function calling](/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.
type ParallelToolCalls *bool

// Static predicted output content, such as the content of a text file that is
// being regenerated.
type PredictionContent struct {
	// The content that should be matched when generating a model response.
	// If generated tokens would match this content, the entire model response
	// can be returned much more quickly.
	//
	Content PredictionContentContent `json:"content"`
}

// The content used for a Predicted Output. This is often the
// text of a file you are regenerating with minor changes.
type PredictionContentContentString *string

// An array of content parts with a defined type. Supported options differ based on the [model](/docs/models) being used to generate the response. Can contain text inputs.
type PredictionContentContentArray []ChatCompletionRequestMessageContentPartText

// The content that should be matched when generating a model response.
// If generated tokens would match this content, the entire model response
// can be returned much more quickly.
type PredictionContentContent struct {
	PredictionContentContentString *PredictionContentContentString
	PredictionContentContentArray  *PredictionContentContentArray
}

func (u *PredictionContentContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.PredictionContentContentString != nil {
		return json.Marshal(u.PredictionContentContentString)
	}
	if u.PredictionContentContentArray != nil {
		return json.Marshal(u.PredictionContentContentArray)
	}
	return nil, errors.New("invalid PredictionContentContent: all variants are nil")
}

func (u *PredictionContentContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = PredictionContentContent{}
	switch raw.(type) {
	case string:
		var v PredictionContentContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.PredictionContentContentString = &v
		return nil
	case []interface{}:
		var v PredictionContentContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.PredictionContentContentArray = &v
		return nil
	}
	return nil
}

// Constrains effort on reasoning for
// [reasoning models](https://platform.openai.com/docs/guides/reasoning).
// Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing
// reasoning effort can result in faster responses and fewer tokens used
// on reasoning in a response.
//
// - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool calls are supported for all reasoning values in gpt-5.1.
// - All models before `gpt-5.1` default to `medium` reasoning effort, and do not support `none`.
// - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
// - `xhigh` is supported for all models after `gpt-5.1-codex-max`.
type ReasoningEffort string

const (
	ReasoningEffortNone    ReasoningEffort = "none"
	ReasoningEffortMinimal ReasoningEffort = "minimal"
	ReasoningEffortLow     ReasoningEffort = "low"
	ReasoningEffortMedium  ReasoningEffort = "medium"
	ReasoningEffortHigh    ReasoningEffort = "high"
	ReasoningEffortXhigh   ReasoningEffort = "xhigh"
)

// Default response format. Used to generate text responses.
type ResponseFormatText struct {
}

// JSON Schema response format. Used to generate structured JSON responses.
// Learn more about [Structured Outputs](/docs/guides/structured-outputs).
type ResponseFormatJsonSchema struct {
	// Structured Outputs configuration options, including a JSON Schema.
	//
	JsonSchema ResponseFormatJsonSchemaJsonSchema `json:"json_schema"`
}

// Structured Outputs configuration options, including a JSON Schema.
type ResponseFormatJsonSchemaJsonSchema struct {
	// A description of what the response format is for, used by the model to
	// determine how to respond in the format.
	//
	Description *string `json:"description,omitempty"`
	// The name of the response format. Must be a-z, A-Z, 0-9, or contain
	// underscores and dashes, with a maximum length of 64.
	//
	Name   string                          `json:"name"`
	Schema *ResponseFormatJsonSchemaSchema `json:"schema,omitempty"`
	// Whether to enable strict schema adherence when generating the output.
	// If set to true, the model will always follow the exact schema defined
	// in the `schema` field. Only a subset of JSON Schema is supported when
	// `strict` is `true`. To learn more, read the [Structured Outputs
	// guide](/docs/guides/structured-outputs).
	//
	Strict *bool `json:"strict,omitempty"`
}

// JSON object response format. An older method of generating JSON responses.
// Using `json_schema` is recommended for models that support it. Note that the
// model will not generate JSON without a system or user message instructing it
// to do so.
type ResponseFormatJsonObject struct {
}

type StopConfigurationString *string

type StopConfigurationArray []string

// Not supported with latest reasoning models `o3` and `o4-mini`.
//
// Up to 4 sequences where the API will stop generating further tokens. The
// returned text will not contain the stop sequence.
type StopConfiguration struct {
	StopConfigurationString *StopConfigurationString
	StopConfigurationArray  *StopConfigurationArray
}

func (u *StopConfiguration) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.StopConfigurationString != nil {
		return json.Marshal(u.StopConfigurationString)
	}
	if u.StopConfigurationArray != nil {
		return json.Marshal(u.StopConfigurationArray)
	}
	return nil, errors.New("invalid StopConfiguration: all variants are nil")
}

func (u *StopConfiguration) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = StopConfiguration{}
	switch raw.(type) {
	case string:
		var v StopConfigurationString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.StopConfigurationString = &v
		return nil
	case []interface{}:
		var v StopConfigurationArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.StopConfigurationArray = &v
		return nil
	}
	return nil
}

// Options for streaming response. Only set this when you set `stream: true`.
type ChatCompletionStreamOptions struct {
	// When true, stream obfuscation will be enabled. Stream obfuscation adds
	// random characters to an `obfuscation` field on streaming delta events to
	// normalize payload sizes as a mitigation to certain side-channel attacks.
	// These obfuscation fields are included by default, but add a small amount
	// of overhead to the data stream. You can set `include_obfuscation` to
	// false to optimize for bandwidth if you trust the network links between
	// your application and the OpenAI API.
	//
	IncludeObfuscation *bool `json:"include_obfuscation,omitempty"`
	// If set, an additional chunk will be streamed before the `data: [DONE]`
	// message. The `usage` field on this chunk shows the token usage statistics
	// for the entire request, and the `choices` field will always be an empty
	// array.
	//
	// All other chunks will also include a `usage` field, but with a null
	// value. **NOTE:** If the stream is interrupted, you may not receive the
	// final usage chunk which contains the total token usage for the request.
	//
	IncludeUsage *bool `json:"include_usage,omitempty"`
}

// `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools.
type ChatCompletionToolChoiceOptionString *string

// Controls which (if any) tool is called by the model.
// `none` means the model will not call any tool and instead generates a message.
// `auto` means the model can pick between generating a message or calling one or more tools.
// `required` means the model must call one or more tools.
// Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool.
//
// `none` is the default when no tools are present. `auto` is the default if tools are present.
type ChatCompletionToolChoiceOption struct {
	ChatCompletionToolChoiceOptionString *ChatCompletionToolChoiceOptionString
	ChatCompletionAllowedToolsChoice     *ChatCompletionAllowedToolsChoice
	ChatCompletionNamedToolChoice        *ChatCompletionNamedToolChoice
	ChatCompletionNamedToolChoiceCustom  *ChatCompletionNamedToolChoiceCustom
}

func (u *ChatCompletionToolChoiceOption) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionToolChoiceOptionString != nil {
		return json.Marshal(u.ChatCompletionToolChoiceOptionString)
	}
	if u.ChatCompletionAllowedToolsChoice != nil {
		return json.Marshal(u.ChatCompletionAllowedToolsChoice)
	}
	if u.ChatCompletionNamedToolChoice != nil {
		return json.Marshal(u.ChatCompletionNamedToolChoice)
	}
	if u.ChatCompletionNamedToolChoiceCustom != nil {
		return json.Marshal(u.ChatCompletionNamedToolChoiceCustom)
	}
	return nil, errors.New("invalid ChatCompletionToolChoiceOption: all variants are nil")
}

func (u *ChatCompletionToolChoiceOption) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionToolChoiceOption{}
	switch value := raw.(type) {
	case string:
		var v ChatCompletionToolChoiceOptionString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionToolChoiceOptionString = &v
		return nil
	case map[string]interface{}:
		if rawType, ok := value["type"]; (!ok || rawType == "allowed_tools") && value["type"] != nil && value["allowed_tools"] != nil {
			var v ChatCompletionAllowedToolsChoice
			if err := json.Unmarshal(data, &v); err != nil {
				return nil
			}
			u.ChatCompletionAllowedToolsChoice = &v
			return nil
		}
		if rawType, ok := value["type"]; (!ok || rawType == "function") && value["type"] != nil && value["function"] != nil {
			var v ChatCompletionNamedToolChoice
			if err := json.Unmarshal(data, &v); err != nil {
				return nil
			}
			u.ChatCompletionNamedToolChoice = &v
			return nil
		}
		if rawType, ok := value["type"]; (!ok || rawType == "custom") && value["type"] != nil && value["custom"] != nil {
			var v ChatCompletionNamedToolChoiceCustom
			if err := json.Unmarshal(data, &v); err != nil {
				return nil
			}
			u.ChatCompletionNamedToolChoiceCustom = &v
			return nil
		}
		return nil
	}
	return nil
}

// A function tool that can be used to generate a response.
type ChatCompletionTool struct {
	Function FunctionObject `json:"function"`
}

// A custom tool that processes input using a specified format.
type CustomToolChatCompletions struct {
	// Properties of the custom tool.
	//
	Custom CustomToolChatCompletionsCustom `json:"custom"`
}

// Properties of the custom tool.
type CustomToolChatCompletionsCustom struct {
	// Optional description of the custom tool, used to provide more context.
	//
	Description *string `json:"description,omitempty"`
	// The input format for the custom tool. Default is unconstrained text.
	//
	Format *CustomToolChatCompletionsCustomFormat `json:"format,omitempty"`
	// The name of the custom tool, used to identify it in tool calls.
	Name string `json:"name"`
}

// Unconstrained free-form text.
type CustomToolChatCompletionsCustomFormatText struct {
	// Unconstrained text format. Always `text`.
	Type CustomToolChatCompletionsCustomFormatTextType `json:"type"`
}

// Unconstrained text format. Always `text`.
type CustomToolChatCompletionsCustomFormatTextType string

const (
	CustomToolChatCompletionsCustomFormatTextTypeText CustomToolChatCompletionsCustomFormatTextType = "text"
)

// A grammar defined by the user.
type CustomToolChatCompletionsCustomFormatGrammar struct {
	// Your chosen grammar.
	Grammar CustomToolChatCompletionsCustomFormatGrammarGrammar `json:"grammar"`
	// Grammar format. Always `grammar`.
	Type CustomToolChatCompletionsCustomFormatGrammarType `json:"type"`
}

// Your chosen grammar.
type CustomToolChatCompletionsCustomFormatGrammarGrammar struct {
	// The grammar definition.
	Definition string `json:"definition"`
	// The syntax of the grammar definition. One of `lark` or `regex`.
	Syntax CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax `json:"syntax"`
}

// The syntax of the grammar definition. One of `lark` or `regex`.
type CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax string

const (
	CustomToolChatCompletionsCustomFormatGrammarGrammarSyntaxLark  CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax = "lark"
	CustomToolChatCompletionsCustomFormatGrammarGrammarSyntaxRegex CustomToolChatCompletionsCustomFormatGrammarGrammarSyntax = "regex"
)

// Grammar format. Always `grammar`.
type CustomToolChatCompletionsCustomFormatGrammarType string

const (
	CustomToolChatCompletionsCustomFormatGrammarTypeGrammar CustomToolChatCompletionsCustomFormatGrammarType = "grammar"
)

// The input format for the custom tool. Default is unconstrained text.
type CustomToolChatCompletionsCustomFormat struct {
	Text    *CustomToolChatCompletionsCustomFormatText
	Grammar *CustomToolChatCompletionsCustomFormatGrammar
}

func (u *CustomToolChatCompletionsCustomFormat) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*CustomToolChatCompletionsCustomFormatText
		}{
			Type: "text",
			CustomToolChatCompletionsCustomFormatText: u.Text,
		})
	}
	if u.Grammar != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*CustomToolChatCompletionsCustomFormatGrammar
		}{
			Type: "grammar",
			CustomToolChatCompletionsCustomFormatGrammar: u.Grammar,
		})
	}
	return nil, errors.New("invalid CustomToolChatCompletionsCustomFormat: all variants are nil")
}

func (u *CustomToolChatCompletionsCustomFormat) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = CustomToolChatCompletionsCustomFormat{}
	switch discriminator {
	case "text":
		var value CustomToolChatCompletionsCustomFormatText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	case "grammar":
		var value CustomToolChatCompletionsCustomFormatGrammar
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Grammar = &value
	default:
		return nil
	}
	return nil
}

// Constrains the verbosity of the model's response. Lower values will result in
// more concise responses, while higher values will result in more verbose responses.
// Currently supported values are `low`, `medium`, and `high`.
type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

// High level guidance for the amount of context window space to use for the
// search. One of `low`, `medium`, or `high`. `medium` is the default.
type WebSearchContextSize string

const (
	WebSearchContextSizeLow    WebSearchContextSize = "low"
	WebSearchContextSizeMedium WebSearchContextSize = "medium"
	WebSearchContextSizeHigh   WebSearchContextSize = "high"
)

// Approximate location parameters for the search.
type WebSearchLocation struct {
	// Free text input for the city of the user, e.g. `San Francisco`.
	//
	City *string `json:"city,omitempty"`
	// The two-letter
	// [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user,
	// e.g. `US`.
	//
	Country *string `json:"country,omitempty"`
	// Free text input for the region of the user, e.g. `California`.
	//
	Region *string `json:"region,omitempty"`
	// The [IANA timezone](https://timeapi.io/documentation/iana-timezones)
	// of the user, e.g. `America/Los_Angeles`.
	//
	Timezone *string `json:"timezone,omitempty"`
}

type ChatCompletionTokenLogprob struct {
	// A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
	Bytes []int `json:"bytes"`
	// The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
	Logprob float64 `json:"logprob"`
	// The token.
	Token string `json:"token"`
	// List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.
	TopLogprobs []ChatCompletionTokenLogprobTopLogprobsItem `json:"top_logprobs"`
}

type ChatCompletionTokenLogprobTopLogprobsItem struct {
	// A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be `null` if there is no bytes representation for the token.
	Bytes []int `json:"bytes"`
	// The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
	Logprob float64 `json:"logprob"`
	// The token.
	Token string `json:"token"`
}

// A chat completion message generated by the model.
type ChatCompletionResponseMessage struct {
	// Annotations for the message, when applicable, as when using the
	// [web search tool](/docs/guides/tools-web-search?api-mode=chat).
	//
	Annotations []ChatCompletionResponseMessageAnnotationsItem `json:"annotations,omitempty"`
	// If the audio output modality is requested, this object contains data
	// about the audio response from the model. [Learn more](/docs/guides/audio).
	//
	Audio *ChatCompletionResponseMessageAudio `json:"audio,omitempty"`
	// The contents of the message.
	Content *string `json:"content"`
	// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
	FunctionCall *ChatCompletionResponseMessageFunctionCall `json:"function_call,omitempty"`
	// The refusal message generated by the model.
	Refusal *string `json:"refusal"`
	// The role of the author of this message.
	Role      ChatCompletionResponseMessageRole `json:"role"`
	ToolCalls *ChatCompletionMessageToolCalls   `json:"tool_calls,omitempty"`
}

// A URL citation when using web search.
type ChatCompletionResponseMessageAnnotationsItem struct {
	// The type of the URL citation. Always `url_citation`.
	Type ChatCompletionResponseMessageAnnotationsItemType `json:"type"`
	// A URL citation when using web search.
	UrlCitation ChatCompletionResponseMessageAnnotationsItemUrlCitation `json:"url_citation"`
}

// The type of the URL citation. Always `url_citation`.
type ChatCompletionResponseMessageAnnotationsItemType string

const (
	ChatCompletionResponseMessageAnnotationsItemTypeUrlCitation ChatCompletionResponseMessageAnnotationsItemType = "url_citation"
)

// A URL citation when using web search.
type ChatCompletionResponseMessageAnnotationsItemUrlCitation struct {
	// The index of the last character of the URL citation in the message.
	EndIndex int `json:"end_index"`
	// The index of the first character of the URL citation in the message.
	StartIndex int `json:"start_index"`
	// The title of the web resource.
	Title string `json:"title"`
	// The URL of the web resource.
	Url string `json:"url"`
}

// If the audio output modality is requested, this object contains data
// about the audio response from the model. [Learn more](/docs/guides/audio).
type ChatCompletionResponseMessageAudio struct {
	// Base64 encoded audio bytes generated by the model, in the format
	// specified in the request.
	//
	Data string `json:"data"`
	// The Unix timestamp (in seconds) for when this audio response will
	// no longer be accessible on the server for use in multi-turn
	// conversations.
	//
	ExpiresAt int `json:"expires_at"`
	// Unique identifier for this audio response.
	Id string `json:"id"`
	// Transcript of the audio generated by the model.
	Transcript string `json:"transcript"`
}

// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
type ChatCompletionResponseMessageFunctionCall struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments string `json:"arguments"`
	// The name of the function to call.
	Name string `json:"name"`
}

// The role of the author of this message.
type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
)

// Specifies the processing type used for serving the request.
//
//   - If set to 'auto', then the request will be processed with the service tier configured in the Project settings. Unless otherwise configured, the Project will use 'default'.
//
//   - If set to 'default', then the request will be processed with the standard pricing and performance for the selected model.
//
//   - If set to '[flex](/docs/guides/flex-processing)' or '[priority](https://openai.com/api-priority-processing/)', then the request will be processed with the corresponding service tier.
//
//   - When not set, the default behavior is 'auto'.
//
//     When the `service_tier` parameter is set, the response body will include the `service_tier` value based on the processing mode actually used to serve the request. This response value may be different from the value set in the parameter.
type ServiceTier string

const (
	ServiceTierAuto     ServiceTier = "auto"
	ServiceTierDefault  ServiceTier = "default"
	ServiceTierFlex     ServiceTier = "flex"
	ServiceTierScale    ServiceTier = "scale"
	ServiceTierPriority ServiceTier = "priority"
)

// Usage statistics for the completion request.
type CompletionUsage struct {
	// Number of tokens in the generated completion.
	CompletionTokens int `json:"completion_tokens"`
	// Breakdown of tokens used in a completion.
	CompletionTokensDetails *CompletionUsageCompletionTokensDetails `json:"completion_tokens_details,omitempty"`
	// Number of tokens in the prompt.
	PromptTokens int `json:"prompt_tokens"`
	// Breakdown of tokens used in the prompt.
	PromptTokensDetails *CompletionUsagePromptTokensDetails `json:"prompt_tokens_details,omitempty"`
	// Total number of tokens used in the request (prompt + completion).
	TotalTokens int `json:"total_tokens"`
}

// Breakdown of tokens used in a completion.
type CompletionUsageCompletionTokensDetails struct {
	// When using Predicted Outputs, the number of tokens in the
	// prediction that appeared in the completion.
	//
	AcceptedPredictionTokens *int `json:"accepted_prediction_tokens,omitempty"`
	// Audio input tokens generated by the model.
	AudioTokens *int `json:"audio_tokens,omitempty"`
	// Tokens generated by the model for reasoning.
	ReasoningTokens *int `json:"reasoning_tokens,omitempty"`
	// When using Predicted Outputs, the number of tokens in the
	// prediction that did not appear in the completion. However, like
	// reasoning tokens, these tokens are still counted in the total
	// completion tokens for purposes of billing, output, and context window
	// limits.
	//
	RejectedPredictionTokens *int `json:"rejected_prediction_tokens,omitempty"`
}

// Breakdown of tokens used in the prompt.
type CompletionUsagePromptTokensDetails struct {
	// Audio input tokens present in the prompt.
	AudioTokens *int `json:"audio_tokens,omitempty"`
	// Cached tokens present in the prompt.
	CachedTokens *int `json:"cached_tokens,omitempty"`
}

// A chat completion delta generated by streamed model responses.
type ChatCompletionStreamResponseDelta struct {
	Audio *ChatCompletionStreamResponseDeltaAudio `json:"audio,omitempty"`
	// The contents of the chunk message.
	Content *string `json:"content,omitempty"`
	// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
	FunctionCall *ChatCompletionStreamResponseDeltaFunctionCall `json:"function_call,omitempty"`
	// The refusal message generated by the model.
	Refusal *string `json:"refusal,omitempty"`
	// The role of the author of this message.
	Role      *ChatCompletionStreamResponseDeltaRole `json:"role,omitempty"`
	ToolCalls []ChatCompletionMessageToolCallChunk   `json:"tool_calls,omitempty"`
}

// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
type ChatCompletionStreamResponseDeltaFunctionCall struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments *string `json:"arguments,omitempty"`
	// The name of the function to call.
	Name *string `json:"name,omitempty"`
}

// The role of the author of this message.
type ChatCompletionStreamResponseDeltaRole string

const (
	ChatCompletionStreamResponseDeltaRoleDeveloper ChatCompletionStreamResponseDeltaRole = "developer"
	ChatCompletionStreamResponseDeltaRoleSystem    ChatCompletionStreamResponseDeltaRole = "system"
	ChatCompletionStreamResponseDeltaRoleUser      ChatCompletionStreamResponseDeltaRole = "user"
	ChatCompletionStreamResponseDeltaRoleAssistant ChatCompletionStreamResponseDeltaRole = "assistant"
	ChatCompletionStreamResponseDeltaRoleTool      ChatCompletionStreamResponseDeltaRole = "tool"
)

// Partial audio metadata emitted in streamed chat completion deltas.
type ChatCompletionStreamResponseDeltaAudio struct {
	// Base64 encoded audio bytes generated by the model, in the format
	// specified in the request.
	//
	Data *string `json:"data,omitempty"`
	// The Unix timestamp (in seconds) for when this audio response will
	// no longer be accessible on the server for use in multi-turn
	// conversations.
	//
	ExpiresAt *int `json:"expires_at,omitempty"`
	// Unique identifier for this audio response.
	Id *string `json:"id,omitempty"`
	// Transcript of the audio generated by the model.
	Transcript *string `json:"transcript,omitempty"`
}

type ModelResponseProperties struct {
	Metadata *Metadata `json:"metadata,omitempty"`
	// Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](/docs/guides/prompt-caching).
	//
	PromptCacheKey *string `json:"prompt_cache_key,omitempty"`
	// The retention policy for the prompt cache. Set to `24h` to enable extended prompt caching, which keeps cached prefixes active for longer, up to a maximum of 24 hours. [Learn more](/docs/guides/prompt-caching#prompt-cache-retention).
	//
	PromptCacheRetention *ModelResponsePropertiesPromptCacheRetention `json:"prompt_cache_retention,omitempty"`
	// A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
	// The IDs should be a string that uniquely identifies each user, with a maximum length of 64 characters. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
	//
	SafetyIdentifier *string      `json:"safety_identifier,omitempty"`
	ServiceTier      *ServiceTier `json:"service_tier,omitempty"`
	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
	// We generally recommend altering this or `top_p` but not both.
	//
	Temperature *float64 `json:"temperature,omitempty"`
	// An integer between 0 and 20 specifying the number of most likely tokens to
	// return at each token position, each with an associated log probability.
	//
	TopLogprobs *int `json:"top_logprobs,omitempty"`
	// An alternative to sampling with temperature, called nucleus sampling,
	// where the model considers the results of the tokens with top_p probability
	// mass. So 0.1 means only the tokens comprising the top 10% probability mass
	// are considered.
	//
	// We generally recommend altering this or `temperature` but not both.
	//
	TopP *float64 `json:"top_p,omitempty"`
	// This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.
	// A stable identifier for your end-users.
	// Used to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
	//
	User *string `json:"user,omitempty"`
}

// The retention policy for the prompt cache. Set to `24h` to enable extended prompt caching, which keeps cached prefixes active for longer, up to a maximum of 24 hours. [Learn more](/docs/guides/prompt-caching#prompt-cache-retention).
type ModelResponsePropertiesPromptCacheRetention string

const (
	ModelResponsePropertiesPromptCacheRetentionInMemory ModelResponsePropertiesPromptCacheRetention = "in_memory"
	ModelResponsePropertiesPromptCacheRetentionN24H     ModelResponsePropertiesPromptCacheRetention = "24h"
)

type VoiceIdsShared *string

// The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.
//
// Omitting `parameters` defines a function with an empty parameter list.
type FunctionParameters any

// Developer-provided instructions that the model should follow, regardless of
// messages sent by the user. With o1 models and newer, `developer` messages
// replace the previous `system` messages.
type ChatCompletionRequestDeveloperMessage struct {
	// The contents of the developer message.
	Content ChatCompletionRequestDeveloperMessageContent `json:"content"`
	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name *string `json:"name,omitempty"`
}

// The contents of the developer message.
type ChatCompletionRequestDeveloperMessageContentString *string

// An array of content parts with a defined type. For developer messages, only type `text` is supported.
type ChatCompletionRequestDeveloperMessageContentArray []ChatCompletionRequestMessageContentPartText

// The contents of the developer message.
type ChatCompletionRequestDeveloperMessageContent struct {
	ChatCompletionRequestDeveloperMessageContentString *ChatCompletionRequestDeveloperMessageContentString
	ChatCompletionRequestDeveloperMessageContentArray  *ChatCompletionRequestDeveloperMessageContentArray
}

func (u *ChatCompletionRequestDeveloperMessageContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionRequestDeveloperMessageContentString != nil {
		return json.Marshal(u.ChatCompletionRequestDeveloperMessageContentString)
	}
	if u.ChatCompletionRequestDeveloperMessageContentArray != nil {
		return json.Marshal(u.ChatCompletionRequestDeveloperMessageContentArray)
	}
	return nil, errors.New("invalid ChatCompletionRequestDeveloperMessageContent: all variants are nil")
}

func (u *ChatCompletionRequestDeveloperMessageContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionRequestDeveloperMessageContent{}
	switch raw.(type) {
	case string:
		var v ChatCompletionRequestDeveloperMessageContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestDeveloperMessageContentString = &v
		return nil
	case []interface{}:
		var v ChatCompletionRequestDeveloperMessageContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestDeveloperMessageContentArray = &v
		return nil
	}
	return nil
}

// Developer-provided instructions that the model should follow, regardless of
// messages sent by the user. With o1 models and newer, use `developer` messages
// for this purpose instead.
type ChatCompletionRequestSystemMessage struct {
	// The contents of the system message.
	Content ChatCompletionRequestSystemMessageContent `json:"content"`
	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name *string `json:"name,omitempty"`
}

// The contents of the system message.
type ChatCompletionRequestSystemMessageContentString *string

// An array of content parts with a defined type. For system messages, only type `text` is supported.
type ChatCompletionRequestSystemMessageContentArray []ChatCompletionRequestSystemMessageContentPart

// The contents of the system message.
type ChatCompletionRequestSystemMessageContent struct {
	ChatCompletionRequestSystemMessageContentString *ChatCompletionRequestSystemMessageContentString
	ChatCompletionRequestSystemMessageContentArray  *ChatCompletionRequestSystemMessageContentArray
}

func (u *ChatCompletionRequestSystemMessageContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionRequestSystemMessageContentString != nil {
		return json.Marshal(u.ChatCompletionRequestSystemMessageContentString)
	}
	if u.ChatCompletionRequestSystemMessageContentArray != nil {
		return json.Marshal(u.ChatCompletionRequestSystemMessageContentArray)
	}
	return nil, errors.New("invalid ChatCompletionRequestSystemMessageContent: all variants are nil")
}

func (u *ChatCompletionRequestSystemMessageContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionRequestSystemMessageContent{}
	switch raw.(type) {
	case string:
		var v ChatCompletionRequestSystemMessageContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestSystemMessageContentString = &v
		return nil
	case []interface{}:
		var v ChatCompletionRequestSystemMessageContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestSystemMessageContentArray = &v
		return nil
	}
	return nil
}

// Messages sent by an end user, containing prompts or additional context
// information.
type ChatCompletionRequestUserMessage struct {
	// The contents of the user message.
	//
	Content ChatCompletionRequestUserMessageContent `json:"content"`
	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name *string `json:"name,omitempty"`
}

// The text contents of the message.
type ChatCompletionRequestUserMessageContentString *string

// An array of content parts with a defined type. Supported options differ based on the [model](/docs/models) being used to generate the response. Can contain text, image, or audio inputs.
type ChatCompletionRequestUserMessageContentArray []ChatCompletionRequestUserMessageContentPart

// The contents of the user message.
type ChatCompletionRequestUserMessageContent struct {
	ChatCompletionRequestUserMessageContentString *ChatCompletionRequestUserMessageContentString
	ChatCompletionRequestUserMessageContentArray  *ChatCompletionRequestUserMessageContentArray
}

func (u *ChatCompletionRequestUserMessageContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionRequestUserMessageContentString != nil {
		return json.Marshal(u.ChatCompletionRequestUserMessageContentString)
	}
	if u.ChatCompletionRequestUserMessageContentArray != nil {
		return json.Marshal(u.ChatCompletionRequestUserMessageContentArray)
	}
	return nil, errors.New("invalid ChatCompletionRequestUserMessageContent: all variants are nil")
}

func (u *ChatCompletionRequestUserMessageContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionRequestUserMessageContent{}
	switch raw.(type) {
	case string:
		var v ChatCompletionRequestUserMessageContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestUserMessageContentString = &v
		return nil
	case []interface{}:
		var v ChatCompletionRequestUserMessageContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestUserMessageContentArray = &v
		return nil
	}
	return nil
}

// Messages sent by the model in response to user messages.
type ChatCompletionRequestAssistantMessage struct {
	// Data about a previous audio response from the model.
	// [Learn more](/docs/guides/audio).
	//
	Audio *ChatCompletionRequestAssistantMessageAudio `json:"audio,omitempty"`
	// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
	//
	Content *ChatCompletionRequestAssistantMessageContent `json:"content,omitempty"`
	// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
	FunctionCall *ChatCompletionRequestAssistantMessageFunctionCall `json:"function_call,omitempty"`
	// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
	Name *string `json:"name,omitempty"`
	// The refusal message by the assistant.
	Refusal   *string                         `json:"refusal,omitempty"`
	ToolCalls *ChatCompletionMessageToolCalls `json:"tool_calls,omitempty"`
}

// Data about a previous audio response from the model.
// [Learn more](/docs/guides/audio).
type ChatCompletionRequestAssistantMessageAudio struct {
	// Unique identifier for a previous audio response from the model.
	//
	Id string `json:"id"`
}

// The contents of the assistant message.
type ChatCompletionRequestAssistantMessageContentString *string

// An array of content parts with a defined type. Can be one or more of type `text`, or exactly one of type `refusal`.
type ChatCompletionRequestAssistantMessageContentArray []ChatCompletionRequestAssistantMessageContentPart

// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
type ChatCompletionRequestAssistantMessageContent struct {
	ChatCompletionRequestAssistantMessageContentString *ChatCompletionRequestAssistantMessageContentString
	ChatCompletionRequestAssistantMessageContentArray  *ChatCompletionRequestAssistantMessageContentArray
}

func (u *ChatCompletionRequestAssistantMessageContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionRequestAssistantMessageContentString != nil {
		return json.Marshal(u.ChatCompletionRequestAssistantMessageContentString)
	}
	if u.ChatCompletionRequestAssistantMessageContentArray != nil {
		return json.Marshal(u.ChatCompletionRequestAssistantMessageContentArray)
	}
	return nil, errors.New("invalid ChatCompletionRequestAssistantMessageContent: all variants are nil")
}

func (u *ChatCompletionRequestAssistantMessageContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionRequestAssistantMessageContent{}
	switch raw.(type) {
	case string:
		var v ChatCompletionRequestAssistantMessageContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestAssistantMessageContentString = &v
		return nil
	case []interface{}:
		var v ChatCompletionRequestAssistantMessageContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestAssistantMessageContentArray = &v
		return nil
	}
	return nil
}

// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
type ChatCompletionRequestAssistantMessageFunctionCall struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments string `json:"arguments"`
	// The name of the function to call.
	Name string `json:"name"`
}

type ChatCompletionRequestToolMessage struct {
	// The contents of the tool message.
	Content ChatCompletionRequestToolMessageContent `json:"content"`
	// Tool call that this message is responding to.
	ToolCallId string `json:"tool_call_id"`
}

// The contents of the tool message.
type ChatCompletionRequestToolMessageContentString *string

// An array of content parts with a defined type. For tool messages, only type `text` is supported.
type ChatCompletionRequestToolMessageContentArray []ChatCompletionRequestToolMessageContentPart

// The contents of the tool message.
type ChatCompletionRequestToolMessageContent struct {
	ChatCompletionRequestToolMessageContentString *ChatCompletionRequestToolMessageContentString
	ChatCompletionRequestToolMessageContentArray  *ChatCompletionRequestToolMessageContentArray
}

func (u *ChatCompletionRequestToolMessageContent) MarshalJSON() ([]byte, error) {
	if u == nil {
		return []byte("null"), nil
	}
	if u.ChatCompletionRequestToolMessageContentString != nil {
		return json.Marshal(u.ChatCompletionRequestToolMessageContentString)
	}
	if u.ChatCompletionRequestToolMessageContentArray != nil {
		return json.Marshal(u.ChatCompletionRequestToolMessageContentArray)
	}
	return nil, errors.New("invalid ChatCompletionRequestToolMessageContent: all variants are nil")
}

func (u *ChatCompletionRequestToolMessageContent) UnmarshalJSON(data []byte) error {
	var raw interface{}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	*u = ChatCompletionRequestToolMessageContent{}
	switch raw.(type) {
	case string:
		var v ChatCompletionRequestToolMessageContentString
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestToolMessageContentString = &v
		return nil
	case []interface{}:
		var v ChatCompletionRequestToolMessageContentArray
		if err := json.Unmarshal(data, &v); err != nil {
			return nil
		}
		u.ChatCompletionRequestToolMessageContentArray = &v
		return nil
	}
	return nil
}

type ChatCompletionRequestFunctionMessage struct {
	// The contents of the function message.
	Content *string `json:"content"`
	// The name of the function to call.
	Name string `json:"name"`
}

// Learn about [text inputs](/docs/guides/text-generation).
type ChatCompletionRequestMessageContentPartText struct {
	// The text content.
	Text string `json:"text"`
	// The type of the content part.
	Type ChatCompletionRequestMessageContentPartTextType `json:"type"`
}

// The type of the content part.
type ChatCompletionRequestMessageContentPartTextType string

const (
	ChatCompletionRequestMessageContentPartTextTypeText ChatCompletionRequestMessageContentPartTextType = "text"
)

// The schema for the response format, described as a JSON Schema object.
// Learn how to build JSON schemas [here](https://json-schema.org/).
type ResponseFormatJsonSchemaSchema any

// Constrains the tools available to the model to a pre-defined set.
type ChatCompletionAllowedToolsChoice struct {
	AllowedTools ChatCompletionAllowedTools `json:"allowed_tools"`
	// Allowed tool configuration type. Always `allowed_tools`.
	Type ChatCompletionAllowedToolsChoiceType `json:"type"`
}

// Allowed tool configuration type. Always `allowed_tools`.
type ChatCompletionAllowedToolsChoiceType string

const (
	ChatCompletionAllowedToolsChoiceTypeAllowedTools ChatCompletionAllowedToolsChoiceType = "allowed_tools"
)

// Specifies a tool the model should use. Use to force the model to call a specific function.
type ChatCompletionNamedToolChoice struct {
	Function ChatCompletionNamedToolChoiceFunction `json:"function"`
	// For function calling, the type is always `function`.
	Type ChatCompletionNamedToolChoiceType `json:"type"`
}

type ChatCompletionNamedToolChoiceFunction struct {
	// The name of the function to call.
	Name string `json:"name"`
}

// For function calling, the type is always `function`.
type ChatCompletionNamedToolChoiceType string

const (
	ChatCompletionNamedToolChoiceTypeFunction ChatCompletionNamedToolChoiceType = "function"
)

// Specifies a tool the model should use. Use to force the model to call a specific custom tool.
type ChatCompletionNamedToolChoiceCustom struct {
	Custom ChatCompletionNamedToolChoiceCustomCustom `json:"custom"`
	// For custom tool calling, the type is always `custom`.
	Type ChatCompletionNamedToolChoiceCustomType `json:"type"`
}

type ChatCompletionNamedToolChoiceCustomCustom struct {
	// The name of the custom tool to call.
	Name string `json:"name"`
}

// For custom tool calling, the type is always `custom`.
type ChatCompletionNamedToolChoiceCustomType string

const (
	ChatCompletionNamedToolChoiceCustomTypeCustom ChatCompletionNamedToolChoiceCustomType = "custom"
)

type FunctionObject struct {
	// A description of what the function does, used by the model to choose when and how to call the function.
	Description *string `json:"description,omitempty"`
	// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
	Name       string              `json:"name"`
	Parameters *FunctionParameters `json:"parameters,omitempty"`
	// Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](/docs/guides/function-calling).
	Strict *bool `json:"strict,omitempty"`
}

type ChatCompletionMessageToolCallsItem struct {
	Function *ChatCompletionMessageToolCall
	Custom   *ChatCompletionMessageCustomToolCall
}

func (u *ChatCompletionMessageToolCallsItem) MarshalJSON() ([]byte, error) {
	if u.Function != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionMessageToolCall
		}{
			Type:                          "function",
			ChatCompletionMessageToolCall: u.Function,
		})
	}
	if u.Custom != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionMessageCustomToolCall
		}{
			Type:                                "custom",
			ChatCompletionMessageCustomToolCall: u.Custom,
		})
	}
	return nil, errors.New("invalid ChatCompletionMessageToolCallsItem: all variants are nil")
}

func (u *ChatCompletionMessageToolCallsItem) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionMessageToolCallsItem{}
	switch discriminator {
	case "function":
		var value ChatCompletionMessageToolCall
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Function = &value
	case "custom":
		var value ChatCompletionMessageCustomToolCall
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Custom = &value
	default:
		return nil
	}
	return nil
}

// The tool calls generated by the model, such as function calls.
type ChatCompletionMessageToolCalls []ChatCompletionMessageToolCallsItem

type ChatCompletionMessageToolCallChunk struct {
	Function *ChatCompletionMessageToolCallChunkFunction `json:"function,omitempty"`
	// The ID of the tool call.
	Id    *string `json:"id,omitempty"`
	Index int     `json:"index"`
	// The type of the tool. Currently, only `function` is supported.
	Type *ChatCompletionMessageToolCallChunkType `json:"type,omitempty"`
}

type ChatCompletionMessageToolCallChunkFunction struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments *string `json:"arguments,omitempty"`
	// The name of the function to call.
	Name *string `json:"name,omitempty"`
}

// The type of the tool. Currently, only `function` is supported.
type ChatCompletionMessageToolCallChunkType string

const (
	ChatCompletionMessageToolCallChunkTypeFunction ChatCompletionMessageToolCallChunkType = "function"
)

// Set of 16 key-value pairs that can be attached to an object. This can be
// useful for storing additional information about the object in a structured
// format, and querying for objects via API or the dashboard.
//
// Keys are strings with a maximum length of 64 characters. Values are strings
// with a maximum length of 512 characters.
type Metadata map[string]string

type ChatCompletionRequestSystemMessageContentPart struct {
	Text *ChatCompletionRequestMessageContentPartText
}

func (u *ChatCompletionRequestSystemMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartText
		}{
			Type: "text",
			ChatCompletionRequestMessageContentPartText: u.Text,
		})
	}
	return nil, errors.New("invalid ChatCompletionRequestSystemMessageContentPart: all variants are nil")
}

func (u *ChatCompletionRequestSystemMessageContentPart) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionRequestSystemMessageContentPart{}
	switch discriminator {
	case "text":
		var value ChatCompletionRequestMessageContentPartText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	default:
		return nil
	}
	return nil
}

type ChatCompletionRequestUserMessageContentPart struct {
	Text       *ChatCompletionRequestMessageContentPartText
	ImageUrl   *ChatCompletionRequestMessageContentPartImage
	InputAudio *ChatCompletionRequestMessageContentPartAudio
	File       *ChatCompletionRequestMessageContentPartFile
}

func (u *ChatCompletionRequestUserMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartText
		}{
			Type: "text",
			ChatCompletionRequestMessageContentPartText: u.Text,
		})
	}
	if u.ImageUrl != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartImage
		}{
			Type: "image_url",
			ChatCompletionRequestMessageContentPartImage: u.ImageUrl,
		})
	}
	if u.InputAudio != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartAudio
		}{
			Type: "input_audio",
			ChatCompletionRequestMessageContentPartAudio: u.InputAudio,
		})
	}
	if u.File != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartFile
		}{
			Type: "file",
			ChatCompletionRequestMessageContentPartFile: u.File,
		})
	}
	return nil, errors.New("invalid ChatCompletionRequestUserMessageContentPart: all variants are nil")
}

func (u *ChatCompletionRequestUserMessageContentPart) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionRequestUserMessageContentPart{}
	switch discriminator {
	case "text":
		var value ChatCompletionRequestMessageContentPartText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	case "image_url":
		var value ChatCompletionRequestMessageContentPartImage
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.ImageUrl = &value
	case "input_audio":
		var value ChatCompletionRequestMessageContentPartAudio
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.InputAudio = &value
	case "file":
		var value ChatCompletionRequestMessageContentPartFile
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.File = &value
	default:
		return nil
	}
	return nil
}

type ChatCompletionRequestAssistantMessageContentPart struct {
	Text    *ChatCompletionRequestMessageContentPartText
	Refusal *ChatCompletionRequestMessageContentPartRefusal
}

func (u *ChatCompletionRequestAssistantMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartText
		}{
			Type: "text",
			ChatCompletionRequestMessageContentPartText: u.Text,
		})
	}
	if u.Refusal != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartRefusal
		}{
			Type: "refusal",
			ChatCompletionRequestMessageContentPartRefusal: u.Refusal,
		})
	}
	return nil, errors.New("invalid ChatCompletionRequestAssistantMessageContentPart: all variants are nil")
}

func (u *ChatCompletionRequestAssistantMessageContentPart) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionRequestAssistantMessageContentPart{}
	switch discriminator {
	case "text":
		var value ChatCompletionRequestMessageContentPartText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	case "refusal":
		var value ChatCompletionRequestMessageContentPartRefusal
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Refusal = &value
	default:
		return nil
	}
	return nil
}

type ChatCompletionRequestToolMessageContentPart struct {
	Text *ChatCompletionRequestMessageContentPartText
}

func (u *ChatCompletionRequestToolMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.Text != nil {
		return json.Marshal(struct {
			Type string `json:"type"`
			*ChatCompletionRequestMessageContentPartText
		}{
			Type: "text",
			ChatCompletionRequestMessageContentPartText: u.Text,
		})
	}
	return nil, errors.New("invalid ChatCompletionRequestToolMessageContentPart: all variants are nil")
}

func (u *ChatCompletionRequestToolMessageContentPart) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	rawType, ok := raw["type"]
	if !ok {
		return nil
	}
	var discriminator string
	if err := json.Unmarshal(rawType, &discriminator); err != nil {
		return err
	}
	*u = ChatCompletionRequestToolMessageContentPart{}
	switch discriminator {
	case "text":
		var value ChatCompletionRequestMessageContentPartText
		if err := json.Unmarshal(data, &value); err != nil {
			return nil
		}
		u.Text = &value
	default:
		return nil
	}
	return nil
}

// Constrains the tools available to the model to a pre-defined set.
type ChatCompletionAllowedTools struct {
	// Constrains the tools available to the model to a pre-defined set.
	//
	// `auto` allows the model to pick from among the allowed tools and generate a
	// message.
	//
	// `required` requires the model to call one or more of the allowed tools.
	//
	Mode ChatCompletionAllowedToolsMode `json:"mode"`
	// A list of tool definitions that the model should be allowed to call.
	//
	// For the Chat Completions API, the list of tool definitions might look like:
	// ```json
	// [
	//   { "type": "function", "function": { "name": "get_weather" } },
	//   { "type": "function", "function": { "name": "get_time" } }
	// ]
	// ```
	//
	Tools []any `json:"tools"`
}

// Constrains the tools available to the model to a pre-defined set.
//
// `auto` allows the model to pick from among the allowed tools and generate a
// message.
//
// `required` requires the model to call one or more of the allowed tools.
type ChatCompletionAllowedToolsMode string

const (
	ChatCompletionAllowedToolsModeAuto     ChatCompletionAllowedToolsMode = "auto"
	ChatCompletionAllowedToolsModeRequired ChatCompletionAllowedToolsMode = "required"
)

// A call to a function tool created by the model.
type ChatCompletionMessageToolCall struct {
	// The function that the model called.
	Function ChatCompletionMessageToolCallFunction `json:"function"`
	// The ID of the tool call.
	Id string `json:"id"`
}

// The function that the model called.
type ChatCompletionMessageToolCallFunction struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments string `json:"arguments"`
	// The name of the function to call.
	Name string `json:"name"`
}

// A call to a custom tool created by the model.
type ChatCompletionMessageCustomToolCall struct {
	// The custom tool that the model called.
	Custom ChatCompletionMessageCustomToolCallCustom `json:"custom"`
	// The ID of the tool call.
	Id string `json:"id"`
}

// The custom tool that the model called.
type ChatCompletionMessageCustomToolCallCustom struct {
	// The input for the custom tool call generated by the model.
	Input string `json:"input"`
	// The name of the custom tool to call.
	Name string `json:"name"`
}

// Learn about [image inputs](/docs/guides/vision).
type ChatCompletionRequestMessageContentPartImage struct {
	ImageUrl ChatCompletionRequestMessageContentPartImageImageUrl `json:"image_url"`
}

type ChatCompletionRequestMessageContentPartImageImageUrl struct {
	// Specifies the detail level of the image. Learn more in the [Vision guide](/docs/guides/vision#low-or-high-fidelity-image-understanding).
	Detail *ChatCompletionRequestMessageContentPartImageImageUrlDetail `json:"detail,omitempty"`
	// Either a URL of the image or the base64 encoded image data.
	Url string `json:"url"`
}

// Specifies the detail level of the image. Learn more in the [Vision guide](/docs/guides/vision#low-or-high-fidelity-image-understanding).
type ChatCompletionRequestMessageContentPartImageImageUrlDetail string

const (
	ChatCompletionRequestMessageContentPartImageImageUrlDetailAuto ChatCompletionRequestMessageContentPartImageImageUrlDetail = "auto"
	ChatCompletionRequestMessageContentPartImageImageUrlDetailLow  ChatCompletionRequestMessageContentPartImageImageUrlDetail = "low"
	ChatCompletionRequestMessageContentPartImageImageUrlDetailHigh ChatCompletionRequestMessageContentPartImageImageUrlDetail = "high"
)

// Learn about [audio inputs](/docs/guides/audio).
type ChatCompletionRequestMessageContentPartAudio struct {
	InputAudio ChatCompletionRequestMessageContentPartAudioInputAudio `json:"input_audio"`
}

type ChatCompletionRequestMessageContentPartAudioInputAudio struct {
	// Base64 encoded audio data.
	Data string `json:"data"`
	// The format of the encoded audio data. Currently supports "wav" and "mp3".
	//
	Format ChatCompletionRequestMessageContentPartAudioInputAudioFormat `json:"format"`
}

// The format of the encoded audio data. Currently supports "wav" and "mp3".
type ChatCompletionRequestMessageContentPartAudioInputAudioFormat string

const (
	ChatCompletionRequestMessageContentPartAudioInputAudioFormatWav ChatCompletionRequestMessageContentPartAudioInputAudioFormat = "wav"
	ChatCompletionRequestMessageContentPartAudioInputAudioFormatMp3 ChatCompletionRequestMessageContentPartAudioInputAudioFormat = "mp3"
)

// Learn about [file inputs](/docs/guides/text) for text generation.
type ChatCompletionRequestMessageContentPartFile struct {
	File ChatCompletionRequestMessageContentPartFileFile `json:"file"`
}

type ChatCompletionRequestMessageContentPartFileFile struct {
	// The base64 encoded file data, used when passing the file to the model
	// as a string.
	//
	FileData *string `json:"file_data,omitempty"`
	// The ID of an uploaded file to use as input.
	//
	FileId *string `json:"file_id,omitempty"`
	// The name of the file, used when passing the file to the model as a
	// string.
	//
	Filename *string `json:"filename,omitempty"`
}

type ChatCompletionRequestMessageContentPartRefusal struct {
	// The refusal message generated by the model.
	Refusal string `json:"refusal"`
}
