import type { Message, Part, PartialModelResponse } from "@hoangvvo/llm-sdk";

export interface AgentRequest<TContext> {
  /**
   * The input messages to the agent.
   */
  messages: Message[];
  /**
   * The context to be used during tool calling and building system
   */
  context: TContext;
}

export interface AgentResponse {
  /**
   * The full chain of messages, including both input messages and messages
   * generated during the agent's execution.
   */
  new_messages: Message[];

  /**
   * The output content generated by the agent.
   */
  content: Part[];
}

export interface AgentStreamEventPartial extends PartialModelResponse {
  type: "partial";
}

export type AgentStreamEventMessage = {
  type: "message";
} & Message;

export interface AgentStreamEventResponse extends AgentResponse {
  type: "response";
}

export type AgentStreamEvent =
  | AgentStreamEventPartial
  | AgentStreamEventMessage
  | AgentStreamEventResponse;
