// Code generated by scripts/schema-to-code.ts. DO NOT EDIT.

package googleapi

// Request to generate a completion from the model.
type GenerateContentRequest struct {
	// Optional. Tool configuration for any `Tool` specified in the request. Refer to the [Function calling guide](https://ai.google.dev/gemini-api/docs/function-calling#function_calling_mode) for a usage example.
	ToolConfig *ToolConfig `json:"toolConfig,omitempty"`
	// Optional. Configuration options for model generation and outputs.
	GenerationConfig *GenerationConfig `json:"generationConfig,omitempty"`
	// Optional. The service tier of the request.
	ServiceTier *GenerateContentRequestServiceTier `json:"serviceTier,omitempty"`
	// Required. The name of the `Model` to use for generating the completion. Format: `models/{model}`.
	Model *string `json:"model,omitempty"`
	// Optional. A list of unique `SafetySetting` instances for blocking unsafe content. This will be enforced on the `GenerateContentRequest.contents` and `GenerateContentResponse.candidates`. There should not be more than one setting for each `SafetyCategory` type. The API will block any contents and responses that fail to meet the thresholds set by these settings. This list overrides the default settings for each `SafetyCategory` specified in the safety_settings. If there is no `SafetySetting` for a given `SafetyCategory` provided in the list, the API will use the default safety setting for that category. Harm categories HARM_CATEGORY_HATE_SPEECH, HARM_CATEGORY_SEXUALLY_EXPLICIT, HARM_CATEGORY_DANGEROUS_CONTENT, HARM_CATEGORY_HARASSMENT, HARM_CATEGORY_CIVIC_INTEGRITY, HARM_CATEGORY_JAILBREAK are supported. Refer to the [guide](https://ai.google.dev/gemini-api/docs/safety-settings) for detailed information on available safety settings. Also refer to the [Safety guidance](https://ai.google.dev/gemini-api/docs/safety-guidance) to learn how to incorporate safety considerations in your AI applications.
	SafetySettings []SafetySetting `json:"safetySettings,omitempty"`
	// Required. The content of the current conversation with the model. For single-turn queries, this is a single instance. For multi-turn queries like [chat](https://ai.google.dev/gemini-api/docs/text-generation#chat), this is a repeated field that contains the conversation history and the latest request.
	Contents []Content `json:"contents,omitempty"`
	// Optional. A list of `Tools` the `Model` may use to generate the next response. A `Tool` is a piece of code that enables the system to interact with external systems to perform an action, or set of actions, outside of knowledge and scope of the `Model`. Supported `Tool`s are `Function` and `code_execution`. Refer to the [Function calling](https://ai.google.dev/gemini-api/docs/function-calling) and the [Code execution](https://ai.google.dev/gemini-api/docs/code-execution) guides to learn more.
	Tools []Tool `json:"tools,omitempty"`
	// Optional. Developer set [system instruction(s)](https://ai.google.dev/gemini-api/docs/system-instructions). Currently, text only.
	SystemInstruction *Content `json:"systemInstruction,omitempty"`
	// Optional. The name of the content [cached](https://ai.google.dev/gemini-api/docs/caching) to use as context to serve the prediction. Format: `cachedContents/{cachedContent}`
	CachedContent *string `json:"cachedContent,omitempty"`
	// Optional. Configures the logging behavior for a given request. If set, it takes precedence over the project-level logging config.
	Store *bool `json:"store,omitempty"`
}

// Optional. The service tier of the request.
type GenerateContentRequestServiceTier string

const (
	GenerateContentRequestServiceTierUnspecified GenerateContentRequestServiceTier = "unspecified"
	GenerateContentRequestServiceTierStandard    GenerateContentRequestServiceTier = "standard"
	GenerateContentRequestServiceTierFlex        GenerateContentRequestServiceTier = "flex"
	GenerateContentRequestServiceTierPriority    GenerateContentRequestServiceTier = "priority"
)

// Response from the model supporting multiple candidate responses. Safety ratings and content filtering are reported for both prompt in `GenerateContentResponse.prompt_feedback` and for each candidate in `finish_reason` and in `safety_ratings`. The API: - Returns either all requested candidates or none of them - Returns no candidates at all only if there was something wrong with the prompt (check `prompt_feedback`) - Reports feedback on each candidate in `finish_reason` and `safety_ratings`.
type GenerateContentResponse struct {
	// Returns the prompt's feedback related to the content filters.
	PromptFeedback *PromptFeedback `json:"promptFeedback,omitempty"`
	// Output only. The model version used to generate the response.
	ModelVersion *string `json:"modelVersion,omitempty"`
	// Output only. The current model status of this model.
	ModelStatus *ModelStatus `json:"modelStatus,omitempty"`
	// Candidate responses from the model.
	Candidates []Candidate `json:"candidates,omitempty"`
	// Output only. Metadata on the generation requests' token usage.
	UsageMetadata *UsageMetadata `json:"usageMetadata,omitempty"`
	// Output only. response_id is used to identify each response.
	ResponseId *string `json:"responseId,omitempty"`
}

// The Tool configuration containing parameters for specifying `Tool` use in the request.
type ToolConfig struct {
	// Optional. Retrieval config.
	RetrievalConfig *RetrievalConfig `json:"retrievalConfig,omitempty"`
	// Optional. Function calling config.
	FunctionCallingConfig *FunctionCallingConfig `json:"functionCallingConfig,omitempty"`
	// Optional. If true, the API response will include the server-side tool calls and responses within the `Content` message. This allows clients to observe the server's tool interactions.
	IncludeServerSideToolInvocations *bool `json:"includeServerSideToolInvocations,omitempty"`
}

// Configuration options for model generation and outputs. Not all parameters are configurable for every model.
type GenerationConfig struct {
	// Optional. MIME type of the generated candidate text. Supported MIME types are: `text/plain`: (default) Text output. `application/json`: JSON response in the response candidates. `text/x.enum`: ENUM as a string response in the response candidates. Refer to the [docs](https://ai.google.dev/gemini-api/docs/prompting_with_media#plain_text_formats) for a list of all supported text MIME types.
	ResponseMimeType *string `json:"responseMimeType,omitempty"`
	// Optional. The maximum cumulative probability of tokens to consider when sampling. The model uses combined Top-k and Top-p (nucleus) sampling. Tokens are sorted based on their assigned probabilities so that only the most likely tokens are considered. Top-k sampling directly limits the maximum number of tokens to consider, while Nucleus sampling limits the number of tokens based on the cumulative probability. Note: The default value varies by `Model` and is specified by the`Model.top_p` attribute returned from the `getModel` function. An empty `top_k` attribute indicates that the model doesn't apply top-k sampling and doesn't allow setting `top_k` on requests.
	TopP *float64 `json:"topP,omitempty"`
	// Optional. Presence penalty applied to the next token's logprobs if the token has already been seen in the response. This penalty is binary on/off and not dependant on the number of times the token is used (after the first). Use frequency_penalty for a penalty that increases with each use. A positive penalty will discourage the use of tokens that have already been used in the response, increasing the vocabulary. A negative penalty will encourage the use of tokens that have already been used in the response, decreasing the vocabulary.
	PresencePenalty *float64 `json:"presencePenalty,omitempty"`
	// Optional. Seed used in decoding. If not set, the request uses a randomly generated seed.
	Seed *int `json:"seed,omitempty"`
	// Optional. Only valid if response_logprobs=True. This sets the number of top logprobs, including the chosen candidate, to return at each decoding step in the Candidate.logprobs_result. The number must be in the range of [0, 20].
	Logprobs *int `json:"logprobs,omitempty"`
	// Optional. Controls the randomness of the output. Note: The default value varies by model, see the `Model.temperature` attribute of the `Model` returned from the `getModel` function. Values can range from [0.0, 2.0].
	Temperature *float64 `json:"temperature,omitempty"`
	// Optional. Config for image generation. An error will be returned if this field is set for models that don't support these config options.
	ImageConfig *ImageConfig `json:"imageConfig,omitempty"`
	// Optional. The set of character sequences (up to 5) that will stop output generation. If specified, the API will stop at the first appearance of a `stop_sequence`. The stop sequence will not be included as part of the response.
	StopSequences []string `json:"stopSequences,omitempty"`
	// Optional. An internal detail. Use `responseJsonSchema` rather than this field.
	ResponseJsonSchema any `json:"responseJsonSchema,omitempty"`
	// Optional. Number of generated responses to return. If unset, this will default to 1. Please note that this doesn't work for previous generation models (Gemini 1.0 family)
	CandidateCount *int `json:"candidateCount,omitempty"`
	// Optional. Config for thinking features. An error will be returned if this field is set for models that don't support thinking.
	ThinkingConfig *ThinkingConfig `json:"thinkingConfig,omitempty"`
	// Optional. Configuration for the response output format. Allows specifying output configuration per modality (text, audio, image) in a flat structure.
	ResponseFormat *ResponseFormatConfig `json:"responseFormat,omitempty"`
	// Optional. The maximum number of tokens to consider when sampling. Gemini models use Top-p (nucleus) sampling or a combination of Top-k and nucleus sampling. Top-k sampling considers the set of `top_k` most probable tokens. Models running with nucleus sampling don't allow top_k setting. Note: The default value varies by `Model` and is specified by the`Model.top_p` attribute returned from the `getModel` function. An empty `top_k` attribute indicates that the model doesn't apply top-k sampling and doesn't allow setting `top_k` on requests.
	TopK *int `json:"topK,omitempty"`
	// Optional. Frequency penalty applied to the next token's logprobs, multiplied by the number of times each token has been seen in the respponse so far. A positive penalty will discourage the use of tokens that have already been used, proportional to the number of times the token has been used: The more a token is used, the more difficult it is for the model to use that token again increasing the vocabulary of responses. Caution: A _negative_ penalty will encourage the model to reuse tokens proportional to the number of times the token has been used. Small negative values will reduce the vocabulary of a response. Larger negative values will cause the model to start repeating a common token until it hits the max_output_tokens limit.
	FrequencyPenalty *float64 `json:"frequencyPenalty,omitempty"`
	// Optional. If true, export the logprobs results in response.
	ResponseLogprobs *bool `json:"responseLogprobs,omitempty"`
	// Optional. The requested modalities of the response. Represents the set of modalities that the model can return, and should be expected in the response. This is an exact match to the modalities of the response. A model may have multiple combinations of supported modalities. If the requested modalities do not match any of the supported combinations, an error will be returned. An empty list is equivalent to requesting only text.
	ResponseModalities []GenerationConfigResponseModalitiesItem `json:"responseModalities,omitempty"`
	// Optional. Config for translation.
	TranslationConfig *TranslationConfig `json:"translationConfig,omitempty"`
	// Optional. Output schema of the generated candidate text. Schemas must be a subset of the [OpenAPI schema](https://spec.openapis.org/oas/v3.0.3#schema) and can be objects, primitives or arrays. If set, a compatible `response_mime_type` must also be set. Compatible MIME types: `application/json`: Schema for JSON response. Refer to the [JSON text generation guide](https://ai.google.dev/gemini-api/docs/json-mode) for more details.
	ResponseSchema *Schema `json:"responseSchema,omitempty"`
	// Optional. The maximum number of tokens to include in a response candidate. Note: The default value varies by model, see the `Model.output_token_limit` attribute of the `Model` returned from the `getModel` function.
	MaxOutputTokens *int `json:"maxOutputTokens,omitempty"`
	// Optional. The speech generation config.
	SpeechConfig *SpeechConfig `json:"speechConfig,omitempty"`
	// Optional. If specified, the media resolution specified will be used.
	MediaResolution *GenerationConfigMediaResolution `json:"mediaResolution,omitempty"`
	// Optional. Output schema of the generated response. This is an alternative to `response_schema` that accepts [JSON Schema](https://json-schema.org/). If set, `response_schema` must be omitted, but `response_mime_type` is required. While the full JSON Schema may be sent, not all features are supported. Specifically, only the following properties are supported: - `$id` - `$defs` - `$ref` - `$anchor` - `type` - `format` - `title` - `description` - `enum` (for strings and numbers) - `items` - `prefixItems` - `minItems` - `maxItems` - `minimum` - `maximum` - `anyOf` - `oneOf` (interpreted the same as `anyOf`) - `properties` - `additionalProperties` - `required` The non-standard `propertyOrdering` property may also be set. Cyclic references are unrolled to a limited degree and, as such, may only be used within non-required properties. (Nullable properties are not sufficient.) If `$ref` is set on a sub-schema, no other properties, except for than those starting as a `$`, may be set.
	UnderscoreResponseJsonSchema any `json:"_responseJsonSchema,omitempty"`
	// Optional. Enables enhanced civic answers. It may not be available for all models.
	EnableEnhancedCivicAnswers *bool `json:"enableEnhancedCivicAnswers,omitempty"`
}

type GenerationConfigResponseModalitiesItem string

const (
	GenerationConfigResponseModalitiesItemMODALITYUNSPECIFIED GenerationConfigResponseModalitiesItem = "MODALITY_UNSPECIFIED"
	GenerationConfigResponseModalitiesItemTEXT                GenerationConfigResponseModalitiesItem = "TEXT"
	GenerationConfigResponseModalitiesItemIMAGE               GenerationConfigResponseModalitiesItem = "IMAGE"
	GenerationConfigResponseModalitiesItemAUDIO               GenerationConfigResponseModalitiesItem = "AUDIO"
)

// Optional. If specified, the media resolution specified will be used.
type GenerationConfigMediaResolution string

const (
	GenerationConfigMediaResolutionMEDIARESOLUTIONUNSPECIFIED GenerationConfigMediaResolution = "MEDIA_RESOLUTION_UNSPECIFIED"
	GenerationConfigMediaResolutionMEDIARESOLUTIONLOW         GenerationConfigMediaResolution = "MEDIA_RESOLUTION_LOW"
	GenerationConfigMediaResolutionMEDIARESOLUTIONMEDIUM      GenerationConfigMediaResolution = "MEDIA_RESOLUTION_MEDIUM"
	GenerationConfigMediaResolutionMEDIARESOLUTIONHIGH        GenerationConfigMediaResolution = "MEDIA_RESOLUTION_HIGH"
)

// Safety setting, affecting the safety-blocking behavior. Passing a safety setting for a category changes the allowed probability that content is blocked.
type SafetySetting struct {
	// Required. The category for this setting.
	Category *SafetySettingCategory `json:"category,omitempty"`
	// Required. Controls the probability threshold at which harm is blocked.
	Threshold *SafetySettingThreshold `json:"threshold,omitempty"`
}

// Required. The category for this setting.
type SafetySettingCategory string

const (
	SafetySettingCategoryHARMCATEGORYUNSPECIFIED      SafetySettingCategory = "HARM_CATEGORY_UNSPECIFIED"
	SafetySettingCategoryHARMCATEGORYDEROGATORY       SafetySettingCategory = "HARM_CATEGORY_DEROGATORY"
	SafetySettingCategoryHARMCATEGORYTOXICITY         SafetySettingCategory = "HARM_CATEGORY_TOXICITY"
	SafetySettingCategoryHARMCATEGORYVIOLENCE         SafetySettingCategory = "HARM_CATEGORY_VIOLENCE"
	SafetySettingCategoryHARMCATEGORYSEXUAL           SafetySettingCategory = "HARM_CATEGORY_SEXUAL"
	SafetySettingCategoryHARMCATEGORYMEDICAL          SafetySettingCategory = "HARM_CATEGORY_MEDICAL"
	SafetySettingCategoryHARMCATEGORYDANGEROUS        SafetySettingCategory = "HARM_CATEGORY_DANGEROUS"
	SafetySettingCategoryHARMCATEGORYHARASSMENT       SafetySettingCategory = "HARM_CATEGORY_HARASSMENT"
	SafetySettingCategoryHARMCATEGORYHATESPEECH       SafetySettingCategory = "HARM_CATEGORY_HATE_SPEECH"
	SafetySettingCategoryHARMCATEGORYSEXUALLYEXPLICIT SafetySettingCategory = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
	SafetySettingCategoryHARMCATEGORYDANGEROUSCONTENT SafetySettingCategory = "HARM_CATEGORY_DANGEROUS_CONTENT"
	SafetySettingCategoryHARMCATEGORYCIVICINTEGRITY   SafetySettingCategory = "HARM_CATEGORY_CIVIC_INTEGRITY"
	SafetySettingCategoryHARMCATEGORYJAILBREAK        SafetySettingCategory = "HARM_CATEGORY_JAILBREAK"
)

// Required. Controls the probability threshold at which harm is blocked.
type SafetySettingThreshold string

const (
	SafetySettingThresholdHARMBLOCKTHRESHOLDUNSPECIFIED SafetySettingThreshold = "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
	SafetySettingThresholdBLOCKLOWANDABOVE              SafetySettingThreshold = "BLOCK_LOW_AND_ABOVE"
	SafetySettingThresholdBLOCKMEDIUMANDABOVE           SafetySettingThreshold = "BLOCK_MEDIUM_AND_ABOVE"
	SafetySettingThresholdBLOCKONLYHIGH                 SafetySettingThreshold = "BLOCK_ONLY_HIGH"
	SafetySettingThresholdBLOCKNONE                     SafetySettingThreshold = "BLOCK_NONE"
	SafetySettingThresholdOFF                           SafetySettingThreshold = "OFF"
)

// The base structured datatype containing multi-part content of a message. A `Content` includes a `role` field designating the producer of the `Content` and a `parts` field containing multi-part data that contains the content of the message turn.
type Content struct {
	// Optional. The producer of the content. Must be either 'user' or 'model'. Useful to set for multi-turn conversations, otherwise can be left blank or unset.
	Role *string `json:"role,omitempty"`
	// Ordered `Parts` that constitute a single message. Parts may have different MIME types.
	Parts []Part `json:"parts,omitempty"`
}

// Tool details that the model may use to generate response. A `Tool` is a piece of code that enables the system to interact with external systems to perform an action, or set of actions, outside of knowledge and scope of the model. Next ID: 16
type Tool struct {
	// Optional. Enables the model to execute code as part of generation.
	CodeExecution *CodeExecution `json:"codeExecution,omitempty"`
	// Optional. Tool to support URL context retrieval.
	UrlContext *UrlContext `json:"urlContext,omitempty"`
	// Optional. FileSearch tool type. Tool to retrieve knowledge from Semantic Retrieval corpora.
	FileSearch *FileSearch `json:"fileSearch,omitempty"`
	// Optional. A list of `FunctionDeclarations` available to the model that can be used for function calling. The model or system does not execute the function. Instead the defined function may be returned as a FunctionCall with arguments to the client side for execution. The model may decide to call a subset of these functions by populating FunctionCall in the response. The next conversation turn may contain a FunctionResponse with the Content.role "function" generation context for the next model turn.
	FunctionDeclarations []FunctionDeclaration `json:"functionDeclarations,omitempty"`
	// Optional. GoogleSearch tool type. Tool to support Google Search in Model. Powered by Google.
	GoogleSearch *GoogleSearch `json:"googleSearch,omitempty"`
	// Optional. Retrieval tool that is powered by Google search.
	GoogleSearchRetrieval *GoogleSearchRetrieval `json:"googleSearchRetrieval,omitempty"`
	// Optional. MCP Servers to connect to.
	McpServers []McpServer `json:"mcpServers,omitempty"`
	// Optional. Tool that allows grounding the model's response with geospatial context related to the user's query.
	GoogleMaps *GoogleMaps `json:"googleMaps,omitempty"`
	// Optional. Tool to support the model interacting directly with the computer. If enabled, it automatically populates computer-use specific Function Declarations.
	ComputerUse *ComputerUse `json:"computerUse,omitempty"`
}

// A set of the feedback metadata the prompt specified in `GenerateContentRequest.content`.
type PromptFeedback struct {
	// Optional. If set, the prompt was blocked and no candidates are returned. Rephrase the prompt.
	BlockReason *PromptFeedbackBlockReason `json:"blockReason,omitempty"`
	// Ratings for safety of the prompt. There is at most one rating per category.
	SafetyRatings []SafetyRating `json:"safetyRatings,omitempty"`
}

// Optional. If set, the prompt was blocked and no candidates are returned. Rephrase the prompt.
type PromptFeedbackBlockReason string

const (
	PromptFeedbackBlockReasonBLOCKREASONUNSPECIFIED PromptFeedbackBlockReason = "BLOCK_REASON_UNSPECIFIED"
	PromptFeedbackBlockReasonSAFETY                 PromptFeedbackBlockReason = "SAFETY"
	PromptFeedbackBlockReasonOTHER                  PromptFeedbackBlockReason = "OTHER"
	PromptFeedbackBlockReasonBLOCKLIST              PromptFeedbackBlockReason = "BLOCKLIST"
	PromptFeedbackBlockReasonPROHIBITEDCONTENT      PromptFeedbackBlockReason = "PROHIBITED_CONTENT"
	PromptFeedbackBlockReasonIMAGESAFETY            PromptFeedbackBlockReason = "IMAGE_SAFETY"
)

// The status of the underlying model. This is used to indicate the stage of the underlying model and the retirement time if applicable.
type ModelStatus struct {
	// The stage of the underlying model.
	ModelStage *ModelStatusModelStage `json:"modelStage,omitempty"`
	// A message explaining the model status.
	Message *string `json:"message,omitempty"`
	// The time at which the model will be retired.
	RetirementTime *string `json:"retirementTime,omitempty"`
}

// The stage of the underlying model.
type ModelStatusModelStage string

const (
	ModelStatusModelStageMODELSTAGEUNSPECIFIED ModelStatusModelStage = "MODEL_STAGE_UNSPECIFIED"
	ModelStatusModelStageUNSTABLEEXPERIMENTAL  ModelStatusModelStage = "UNSTABLE_EXPERIMENTAL"
	ModelStatusModelStageEXPERIMENTAL          ModelStatusModelStage = "EXPERIMENTAL"
	ModelStatusModelStagePREVIEW               ModelStatusModelStage = "PREVIEW"
	ModelStatusModelStageSTABLE                ModelStatusModelStage = "STABLE"
	ModelStatusModelStageLEGACY                ModelStatusModelStage = "LEGACY"
	ModelStatusModelStageDEPRECATED            ModelStatusModelStage = "DEPRECATED"
	ModelStatusModelStageRETIRED               ModelStatusModelStage = "RETIRED"
)

// A response candidate generated from the model.
type Candidate struct {
	// Output only. Generated content returned from the model.
	Content *Content `json:"content,omitempty"`
	// Output only. Average log probability score of the candidate.
	AvgLogprobs *float64 `json:"avgLogprobs,omitempty"`
	// Output only. Token count for this candidate.
	TokenCount *int `json:"tokenCount,omitempty"`
	// Optional. Output only. Details the reason why the model stopped generating tokens. This is populated only when `finish_reason` is set.
	FinishMessage *string `json:"finishMessage,omitempty"`
	// List of ratings for the safety of a response candidate. There is at most one rating per category.
	SafetyRatings []SafetyRating `json:"safetyRatings,omitempty"`
	// Output only. Log-likelihood scores for the response tokens and top tokens
	LogprobsResult *LogprobsResult `json:"logprobsResult,omitempty"`
	// Output only. Attribution information for sources that contributed to a grounded answer. This field is populated for `GenerateAnswer` calls.
	GroundingAttributions []GroundingAttribution `json:"groundingAttributions,omitempty"`
	// Output only. Metadata related to url context retrieval tool.
	UrlContextMetadata *UrlContextMetadata `json:"urlContextMetadata,omitempty"`
	// Output only. Index of the candidate in the list of response candidates.
	Index *int `json:"index,omitempty"`
	// Optional. Output only. The reason why the model stopped generating tokens. If empty, the model has not stopped generating tokens.
	FinishReason *CandidateFinishReason `json:"finishReason,omitempty"`
	// Output only. Citation information for model-generated candidate. This field may be populated with recitation information for any text included in the `content`. These are passages that are "recited" from copyrighted material in the foundational LLM's training data.
	CitationMetadata *CitationMetadata `json:"citationMetadata,omitempty"`
	// Output only. Grounding metadata for the candidate. This field is populated for `GenerateContent` calls.
	GroundingMetadata *GroundingMetadata `json:"groundingMetadata,omitempty"`
}

// Optional. Output only. The reason why the model stopped generating tokens. If empty, the model has not stopped generating tokens.
type CandidateFinishReason string

const (
	CandidateFinishReasonFINISHREASONUNSPECIFIED CandidateFinishReason = "FINISH_REASON_UNSPECIFIED"
	CandidateFinishReasonSTOP                    CandidateFinishReason = "STOP"
	CandidateFinishReasonMAXTOKENS               CandidateFinishReason = "MAX_TOKENS"
	CandidateFinishReasonSAFETY                  CandidateFinishReason = "SAFETY"
	CandidateFinishReasonRECITATION              CandidateFinishReason = "RECITATION"
	CandidateFinishReasonLANGUAGE                CandidateFinishReason = "LANGUAGE"
	CandidateFinishReasonOTHER                   CandidateFinishReason = "OTHER"
	CandidateFinishReasonBLOCKLIST               CandidateFinishReason = "BLOCKLIST"
	CandidateFinishReasonPROHIBITEDCONTENT       CandidateFinishReason = "PROHIBITED_CONTENT"
	CandidateFinishReasonSPII                    CandidateFinishReason = "SPII"
	CandidateFinishReasonMALFORMEDFUNCTIONCALL   CandidateFinishReason = "MALFORMED_FUNCTION_CALL"
	CandidateFinishReasonIMAGESAFETY             CandidateFinishReason = "IMAGE_SAFETY"
	CandidateFinishReasonIMAGEPROHIBITEDCONTENT  CandidateFinishReason = "IMAGE_PROHIBITED_CONTENT"
	CandidateFinishReasonIMAGEOTHER              CandidateFinishReason = "IMAGE_OTHER"
	CandidateFinishReasonNOIMAGE                 CandidateFinishReason = "NO_IMAGE"
	CandidateFinishReasonIMAGERECITATION         CandidateFinishReason = "IMAGE_RECITATION"
	CandidateFinishReasonUNEXPECTEDTOOLCALL      CandidateFinishReason = "UNEXPECTED_TOOL_CALL"
	CandidateFinishReasonTOOMANYTOOLCALLS        CandidateFinishReason = "TOO_MANY_TOOL_CALLS"
	CandidateFinishReasonMISSINGTHOUGHTSIGNATURE CandidateFinishReason = "MISSING_THOUGHT_SIGNATURE"
	CandidateFinishReasonMALFORMEDRESPONSE       CandidateFinishReason = "MALFORMED_RESPONSE"
	CandidateFinishReasonESCALATION              CandidateFinishReason = "ESCALATION"
)

// Metadata on the generation request's token usage.
type UsageMetadata struct {
	// Output only. List of modalities of the cached content in the request input.
	CacheTokensDetails []ModalityTokenCount `json:"cacheTokensDetails,omitempty"`
	// Output only. Service tier of the request.
	ServiceTier *UsageMetadataServiceTier `json:"serviceTier,omitempty"`
	// Output only. Number of tokens present in tool-use prompt(s).
	ToolUsePromptTokenCount *int `json:"toolUsePromptTokenCount,omitempty"`
	// Total token count for the generation request (prompt + thoughts + response candidates).
	TotalTokenCount *int `json:"totalTokenCount,omitempty"`
	// Total number of tokens across all the generated response candidates.
	CandidatesTokenCount *int `json:"candidatesTokenCount,omitempty"`
	// Output only. Number of tokens of thoughts for thinking models.
	ThoughtsTokenCount *int `json:"thoughtsTokenCount,omitempty"`
	// Output only. List of modalities that were returned in the response.
	CandidatesTokensDetails []ModalityTokenCount `json:"candidatesTokensDetails,omitempty"`
	// Output only. List of modalities that were processed for tool-use request inputs.
	ToolUsePromptTokensDetails []ModalityTokenCount `json:"toolUsePromptTokensDetails,omitempty"`
	// Number of tokens in the prompt. When `cached_content` is set, this is still the total effective prompt size meaning this includes the number of tokens in the cached content.
	PromptTokenCount *int `json:"promptTokenCount,omitempty"`
	// Output only. List of modalities that were processed in the request input.
	PromptTokensDetails []ModalityTokenCount `json:"promptTokensDetails,omitempty"`
	// Number of tokens in the cached part of the prompt (the cached content)
	CachedContentTokenCount *int `json:"cachedContentTokenCount,omitempty"`
}

// Output only. Service tier of the request.
type UsageMetadataServiceTier string

const (
	UsageMetadataServiceTierUnspecified UsageMetadataServiceTier = "unspecified"
	UsageMetadataServiceTierStandard    UsageMetadataServiceTier = "standard"
	UsageMetadataServiceTierFlex        UsageMetadataServiceTier = "flex"
	UsageMetadataServiceTierPriority    UsageMetadataServiceTier = "priority"
)

// Retrieval config.
type RetrievalConfig struct {
	// Optional. The language code of the user. Language code for content. Use language tags defined by [BCP47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt).
	LanguageCode *string `json:"languageCode,omitempty"`
	// Optional. The location of the user.
	LatLng *LatLng `json:"latLng,omitempty"`
}

// Configuration for specifying function calling behavior.
type FunctionCallingConfig struct {
	// Optional. Specifies the mode in which function calling should execute. If unspecified, the default value will be set to AUTO.
	Mode *FunctionCallingConfigMode `json:"mode,omitempty"`
	// Optional. A set of function names that, when provided, limits the functions the model will call. This should only be set when the Mode is ANY or VALIDATED. Function names should match [FunctionDeclaration.name]. When set, model will predict a function call from only allowed function names.
	AllowedFunctionNames []string `json:"allowedFunctionNames,omitempty"`
}

// Optional. Specifies the mode in which function calling should execute. If unspecified, the default value will be set to AUTO.
type FunctionCallingConfigMode string

const (
	FunctionCallingConfigModeMODEUNSPECIFIED FunctionCallingConfigMode = "MODE_UNSPECIFIED"
	FunctionCallingConfigModeAUTO            FunctionCallingConfigMode = "AUTO"
	FunctionCallingConfigModeANY             FunctionCallingConfigMode = "ANY"
	FunctionCallingConfigModeNONE            FunctionCallingConfigMode = "NONE"
	FunctionCallingConfigModeVALIDATED       FunctionCallingConfigMode = "VALIDATED"
)

// Config for image generation features.
type ImageConfig struct {
	// Optional. The aspect ratio of the image to generate. Supported aspect ratios: `1:1`, `1:4`, `4:1`, `1:8`, `8:1`, `2:3`, `3:2`, `3:4`, `4:3`, `4:5`, `5:4`, `9:16`, `16:9`, or `21:9`. If not specified, the model will choose a default aspect ratio based on any reference images provided.
	AspectRatio *string `json:"aspectRatio,omitempty"`
	// Optional. Specifies the size of generated images. Supported values are `512`, `1K`, `2K`, `4K`. If not specified, the model will use default value `1K`.
	ImageSize *string `json:"imageSize,omitempty"`
}

// Config for thinking features.
type ThinkingConfig struct {
	// Indicates whether to include thoughts in the response. If true, thoughts are returned only when available.
	IncludeThoughts *bool `json:"includeThoughts,omitempty"`
	// The number of thoughts tokens that the model should generate.
	ThinkingBudget *int `json:"thinkingBudget,omitempty"`
	// Optional. Controls the maximum depth of the model's internal reasoning process before it produces a response. The default value is model-dependent. Refer to the [Thinking levels guide](https://ai.google.dev/gemini-api/docs/thinking#thinking-levels) for more details. Recommended for Gemini 3 or later models. Use with earlier models results in an error.
	ThinkingLevel *ThinkingConfigThinkingLevel `json:"thinkingLevel,omitempty"`
}

// Optional. Controls the maximum depth of the model's internal reasoning process before it produces a response. The default value is model-dependent. Refer to the [Thinking levels guide](https://ai.google.dev/gemini-api/docs/thinking#thinking-levels) for more details. Recommended for Gemini 3 or later models. Use with earlier models results in an error.
type ThinkingConfigThinkingLevel string

const (
	ThinkingConfigThinkingLevelTHINKINGLEVELUNSPECIFIED ThinkingConfigThinkingLevel = "THINKING_LEVEL_UNSPECIFIED"
	ThinkingConfigThinkingLevelMINIMAL                  ThinkingConfigThinkingLevel = "MINIMAL"
	ThinkingConfigThinkingLevelLOW                      ThinkingConfigThinkingLevel = "LOW"
	ThinkingConfigThinkingLevelMEDIUM                   ThinkingConfigThinkingLevel = "MEDIUM"
	ThinkingConfigThinkingLevelHIGH                     ThinkingConfigThinkingLevel = "HIGH"
)

// Configuration for the response output format. This is a flat object where each optional sub-field configures a specific output modality.
type ResponseFormatConfig struct {
	// Optional. Audio output format configuration.
	Audio *AudioResponseFormat `json:"audio,omitempty"`
	// Optional. Text output format configuration.
	Text *TextResponseFormat `json:"text,omitempty"`
	// Optional. Image output format configuration.
	Image *ImageResponseFormat `json:"image,omitempty"`
}

// Config for translation features.
type TranslationConfig struct {
	// Optional. If true, the model will generate audio when the target language is spoken, essentially it will parrot the input. If false, we will not produce audio for the target language.
	EchoTargetLanguage *bool `json:"echoTargetLanguage,omitempty"`
	// Required. The target language for translation. Supported values are BCP-47 language codes (e.g. "en", "es", "fr").
	TargetLanguageCode *string `json:"targetLanguageCode,omitempty"`
}

// The `Schema` object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. Represents a select subset of an [OpenAPI 3.0 schema object](https://spec.openapis.org/oas/v3.0.3#schema).
type Schema struct {
	// Optional. The title of the schema.
	Title *string `json:"title,omitempty"`
	// Optional. A brief description of the parameter. This could contain examples of use. Parameter description may be formatted as Markdown.
	Description *string `json:"description,omitempty"`
	// Optional. Minimum number of the elements for Type.ARRAY.
	MinItems *string `json:"minItems,omitempty"`
	// Optional. SCHEMA FIELDS FOR TYPE INTEGER and NUMBER Minimum value of the Type.INTEGER and Type.NUMBER
	Minimum *float64 `json:"minimum,omitempty"`
	// Optional. Maximum number of the elements for Type.ARRAY.
	MaxItems *string `json:"maxItems,omitempty"`
	// Optional. Pattern of the Type.STRING to restrict a string to a regular expression.
	Pattern *string `json:"pattern,omitempty"`
	// Optional. Schema of the elements of Type.ARRAY.
	Items *Schema `json:"items,omitempty"`
	// Optional. Example of the object. Will only populated when the object is the root.
	Example any `json:"example,omitempty"`
	// Optional. The format of the data. Any value is allowed, but most do not trigger any special functionality.
	Format *string `json:"format,omitempty"`
	// Optional. Maximum number of the properties for Type.OBJECT.
	MaxProperties *string `json:"maxProperties,omitempty"`
	// Optional. SCHEMA FIELDS FOR TYPE STRING Minimum length of the Type.STRING
	MinLength *string `json:"minLength,omitempty"`
	// Optional. Required properties of Type.OBJECT.
	Required []string `json:"required,omitempty"`
	// Optional. Minimum number of the properties for Type.OBJECT.
	MinProperties *string `json:"minProperties,omitempty"`
	// Optional. The value should be validated against any (one or more) of the subschemas in the list.
	AnyOf []Schema `json:"anyOf,omitempty"`
	// Required. Data type.
	Type *SchemaType `json:"type,omitempty"`
	// Optional. The order of the properties. Not a standard field in open api spec. Used to determine the order of the properties in the response.
	PropertyOrdering []string `json:"propertyOrdering,omitempty"`
	// Optional. Possible values of the element of Type.STRING with enum format. For example we can define an Enum Direction as : {type:STRING, format:enum, enum:["EAST", NORTH", "SOUTH", "WEST"]}
	Enum []string `json:"enum,omitempty"`
	// Optional. Properties of Type.OBJECT.
	Properties map[string]Schema `json:"properties,omitempty"`
	// Optional. Maximum length of the Type.STRING
	MaxLength *string `json:"maxLength,omitempty"`
	// Optional. Indicates if the value may be null.
	Nullable *bool `json:"nullable,omitempty"`
	// Optional. Maximum value of the Type.INTEGER and Type.NUMBER
	Maximum *float64 `json:"maximum,omitempty"`
	// Optional. Default value of the field. Per JSON Schema, this field is intended for documentation generators and doesn't affect validation. Thus it's included here and ignored so that developers who send schemas with a `default` field don't get unknown-field errors.
	Default any `json:"default,omitempty"`
}

// Required. Data type.
type SchemaType string

const (
	SchemaTypeTYPEUNSPECIFIED SchemaType = "TYPE_UNSPECIFIED"
	SchemaTypeSTRING          SchemaType = "STRING"
	SchemaTypeNUMBER          SchemaType = "NUMBER"
	SchemaTypeINTEGER         SchemaType = "INTEGER"
	SchemaTypeBOOLEAN         SchemaType = "BOOLEAN"
	SchemaTypeARRAY           SchemaType = "ARRAY"
	SchemaTypeOBJECT          SchemaType = "OBJECT"
	SchemaTypeNULL            SchemaType = "NULL"
)

// Config for speech generation and transcription.
type SpeechConfig struct {
	// Optional. The configuration for the multi-speaker setup. It is mutually exclusive with the voice_config field.
	MultiSpeakerVoiceConfig *MultiSpeakerVoiceConfig `json:"multiSpeakerVoiceConfig,omitempty"`
	// The configuration in case of single-voice output.
	VoiceConfig *VoiceConfig `json:"voiceConfig,omitempty"`
	// Optional. The IETF [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language code that the user configured the app to use. Used for speech recognition and synthesis. Valid values are: `de-DE`, `en-AU`, `en-GB`, `en-IN`, `en-US`, `es-US`, `fr-FR`, `hi-IN`, `pt-BR`, `ar-XA`, `es-ES`, `fr-CA`, `id-ID`, `it-IT`, `ja-JP`, `tr-TR`, `vi-VN`, `bn-IN`, `gu-IN`, `kn-IN`, `ml-IN`, `mr-IN`, `ta-IN`, `te-IN`, `nl-NL`, `ko-KR`, `cmn-CN`, `pl-PL`, `ru-RU`, and `th-TH`.
	LanguageCode *string `json:"languageCode,omitempty"`
}

// A datatype containing media that is part of a multi-part `Content` message. A `Part` consists of data which has an associated datatype. A `Part` can only contain one of the accepted types in `Part.data`. A `Part` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.
type Part struct {
	// Optional. Video metadata. The metadata should only be specified while the video data is presented in inline_data or file_data.
	VideoMetadata *VideoMetadata `json:"videoMetadata,omitempty"`
	// Custom metadata associated with the Part. Agents using genai.Part as content representation may need to keep track of the additional information. For example it can be name of a file/source from which the Part originates or a way to multiplex multiple Part streams.
	PartMetadata map[string]any `json:"partMetadata,omitempty"`
	// Code generated by the model that is meant to be executed.
	ExecutableCode *ExecutableCode `json:"executableCode,omitempty"`
	// Optional. Indicates if the part is thought from the model.
	Thought *bool `json:"thought,omitempty"`
	// Result of executing the `ExecutableCode`.
	CodeExecutionResult *CodeExecutionResult `json:"codeExecutionResult,omitempty"`
	// Optional. Media resolution for the input media.
	MediaResolution *MediaResolution `json:"mediaResolution,omitempty"`
	// A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.
	FunctionCall *FunctionCall `json:"functionCall,omitempty"`
	// Server-side tool call. This field is populated when the model predicts a tool invocation that should be executed on the server. The client is expected to echo this message back to the API.
	ToolCall *ToolCall `json:"toolCall,omitempty"`
	// The output from a server-side `ToolCall` execution. This field is populated by the client with the results of executing the corresponding `ToolCall`.
	ToolResponse *ToolResponse `json:"toolResponse,omitempty"`
	// URI based data.
	FileData *FileData `json:"fileData,omitempty"`
	// Inline media bytes.
	InlineData *Blob `json:"inlineData,omitempty"`
	// Optional. An opaque signature for the thought so it can be reused in subsequent requests.
	ThoughtSignature *string `json:"thoughtSignature,omitempty"`
	// The result output of a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model.
	FunctionResponse *FunctionResponse `json:"functionResponse,omitempty"`
	// Inline text.
	Text *string `json:"text,omitempty"`
}

// Tool that executes code generated by the model, and automatically returns the result to the model. See also `ExecutableCode` and `CodeExecutionResult` which are only generated when using this tool.
type CodeExecution any

// Tool to support URL context retrieval.
type UrlContext any

// The FileSearch tool that retrieves knowledge from Semantic Retrieval corpora. Files are imported to Semantic Retrieval corpora using the ImportFile API.
type FileSearch struct {
	// Optional. Metadata filter to apply to the semantic retrieval documents and chunks.
	MetadataFilter *string `json:"metadataFilter,omitempty"`
	// Required. The names of the file_search_stores to retrieve from. Example: `fileSearchStores/my-file-search-store-123`
	FileSearchStoreNames []string `json:"fileSearchStoreNames,omitempty"`
	// Optional. The number of semantic retrieval chunks to retrieve.
	TopK *int `json:"topK,omitempty"`
}

// Structured representation of a function declaration as defined by the [OpenAPI 3.03 specification](https://spec.openapis.org/oas/v3.0.3). Included in this declaration are the function name and parameters. This FunctionDeclaration is a representation of a block of code that can be used as a `Tool` by the model and executed by the client.
type FunctionDeclaration struct {
	// Optional. Describes the output from this function in JSON Schema format. Reflects the Open API 3.03 Response Object. The Schema defines the type used for the response value of the function.
	Response *Schema `json:"response,omitempty"`
	// Required. A brief description of the function.
	Description *string `json:"description,omitempty"`
	// Optional. Describes the parameters to the function in JSON Schema format. The schema must describe an object where the properties are the parameters to the function. For example: ``` { "type": "object", "properties": { "name": { "type": "string" }, "age": { "type": "integer" } }, "additionalProperties": false, "required": ["name", "age"], "propertyOrdering": ["name", "age"] } ``` This field is mutually exclusive with `parameters`.
	ParametersJsonSchema any `json:"parametersJsonSchema,omitempty"`
	// Required. The name of the function. Must be a-z, A-Z, 0-9, or contain underscores, colons, dots, and dashes, with a maximum length of 128.
	Name *string `json:"name,omitempty"`
	// Optional. Specifies the function Behavior. Currently only supported by the BidiGenerateContent method.
	Behavior *FunctionDeclarationBehavior `json:"behavior,omitempty"`
	// Optional. Describes the parameters to this function. Reflects the Open API 3.03 Parameter Object string Key: the name of the parameter. Parameter names are case sensitive. Schema Value: the Schema defining the type used for the parameter.
	Parameters *Schema `json:"parameters,omitempty"`
	// Optional. Describes the output from this function in JSON Schema format. The value specified by the schema is the response value of the function. This field is mutually exclusive with `response`.
	ResponseJsonSchema any `json:"responseJsonSchema,omitempty"`
}

// Optional. Specifies the function Behavior. Currently only supported by the BidiGenerateContent method.
type FunctionDeclarationBehavior string

const (
	FunctionDeclarationBehaviorUNSPECIFIED FunctionDeclarationBehavior = "UNSPECIFIED"
	FunctionDeclarationBehaviorBLOCKING    FunctionDeclarationBehavior = "BLOCKING"
	FunctionDeclarationBehaviorNONBLOCKING FunctionDeclarationBehavior = "NON_BLOCKING"
)

// GoogleSearch tool type. Tool to support Google Search in Model. Powered by Google.
type GoogleSearch struct {
	// Optional. Filter search results to a specific time range. If customers set a start time, they must set an end time (and vice versa).
	TimeRangeFilter *Interval `json:"timeRangeFilter,omitempty"`
	// Optional. The set of search types to enable. If not set, web search is enabled by default.
	SearchTypes *SearchTypes `json:"searchTypes,omitempty"`
}

// Tool to retrieve public web data for grounding, powered by Google.
type GoogleSearchRetrieval struct {
	// Specifies the dynamic retrieval configuration for the given source.
	DynamicRetrievalConfig *DynamicRetrievalConfig `json:"dynamicRetrievalConfig,omitempty"`
}

// A MCPServer is a server that can be called by the model to perform actions. It is a server that implements the MCP protocol. Next ID: 6
type McpServer struct {
	// A transport that can stream HTTP requests and responses.
	StreamableHttpTransport *StreamableHttpTransport `json:"streamableHttpTransport,omitempty"`
	// The name of the MCPServer.
	Name *string `json:"name,omitempty"`
}

// The GoogleMaps Tool that provides geospatial context for the user's query.
type GoogleMaps struct {
	// Optional. Whether to return a widget context token in the GroundingMetadata of the response. Developers can use the widget context token to render a Google Maps widget with geospatial context related to the places that the model references in the response.
	EnableWidget *bool `json:"enableWidget,omitempty"`
}

// Computer Use tool type.
type ComputerUse struct {
	// Optional. Disabled safety policies for computer use.
	DisabledSafetyPolicies []ComputerUseDisabledSafetyPoliciesItem `json:"disabledSafetyPolicies,omitempty"`
	// Optional. By default, predefined functions are included in the final model call. Some of them can be explicitly excluded from being automatically included. This can serve two purposes: 1. Using a more restricted / different action space. 2. Improving the definitions / instructions of predefined functions.
	ExcludedPredefinedFunctions []string `json:"excludedPredefinedFunctions,omitempty"`
	// Required. The environment being operated.
	Environment *ComputerUseEnvironment `json:"environment,omitempty"`
	// Optional. Whether enable the prompt injection detection check on computer-use request.
	EnablePromptInjectionDetection *bool `json:"enablePromptInjectionDetection,omitempty"`
}

type ComputerUseDisabledSafetyPoliciesItem string

const (
	ComputerUseDisabledSafetyPoliciesItemSAFETYPOLICYUNSPECIFIED   ComputerUseDisabledSafetyPoliciesItem = "SAFETY_POLICY_UNSPECIFIED"
	ComputerUseDisabledSafetyPoliciesItemFINANCIALTRANSACTIONS     ComputerUseDisabledSafetyPoliciesItem = "FINANCIAL_TRANSACTIONS"
	ComputerUseDisabledSafetyPoliciesItemSENSITIVEDATAMODIFICATION ComputerUseDisabledSafetyPoliciesItem = "SENSITIVE_DATA_MODIFICATION"
	ComputerUseDisabledSafetyPoliciesItemCOMMUNICATIONTOOL         ComputerUseDisabledSafetyPoliciesItem = "COMMUNICATION_TOOL"
	ComputerUseDisabledSafetyPoliciesItemACCOUNTCREATION           ComputerUseDisabledSafetyPoliciesItem = "ACCOUNT_CREATION"
	ComputerUseDisabledSafetyPoliciesItemDATAMODIFICATION          ComputerUseDisabledSafetyPoliciesItem = "DATA_MODIFICATION"
	ComputerUseDisabledSafetyPoliciesItemUSERCONSENTMANAGEMENT     ComputerUseDisabledSafetyPoliciesItem = "USER_CONSENT_MANAGEMENT"
	ComputerUseDisabledSafetyPoliciesItemLEGALTERMSANDAGREEMENTS   ComputerUseDisabledSafetyPoliciesItem = "LEGAL_TERMS_AND_AGREEMENTS"
)

// Required. The environment being operated.
type ComputerUseEnvironment string

const (
	ComputerUseEnvironmentENVIRONMENTUNSPECIFIED ComputerUseEnvironment = "ENVIRONMENT_UNSPECIFIED"
	ComputerUseEnvironmentENVIRONMENTBROWSER     ComputerUseEnvironment = "ENVIRONMENT_BROWSER"
	ComputerUseEnvironmentENVIRONMENTMOBILE      ComputerUseEnvironment = "ENVIRONMENT_MOBILE"
	ComputerUseEnvironmentENVIRONMENTDESKTOP     ComputerUseEnvironment = "ENVIRONMENT_DESKTOP"
)

// Safety rating for a piece of content. The safety rating contains the category of harm and the harm probability level in that category for a piece of content. Content is classified for safety across a number of harm categories and the probability of the harm classification is included here.
type SafetyRating struct {
	// Required. The probability of harm for this content.
	Probability *SafetyRatingProbability `json:"probability,omitempty"`
	// Required. The category for this rating.
	Category *SafetyRatingCategory `json:"category,omitempty"`
	// Was this content blocked because of this rating?
	Blocked *bool `json:"blocked,omitempty"`
}

// Required. The probability of harm for this content.
type SafetyRatingProbability string

const (
	SafetyRatingProbabilityHARMPROBABILITYUNSPECIFIED SafetyRatingProbability = "HARM_PROBABILITY_UNSPECIFIED"
	SafetyRatingProbabilityNEGLIGIBLE                 SafetyRatingProbability = "NEGLIGIBLE"
	SafetyRatingProbabilityLOW                        SafetyRatingProbability = "LOW"
	SafetyRatingProbabilityMEDIUM                     SafetyRatingProbability = "MEDIUM"
	SafetyRatingProbabilityHIGH                       SafetyRatingProbability = "HIGH"
)

// Required. The category for this rating.
type SafetyRatingCategory string

const (
	SafetyRatingCategoryHARMCATEGORYUNSPECIFIED      SafetyRatingCategory = "HARM_CATEGORY_UNSPECIFIED"
	SafetyRatingCategoryHARMCATEGORYDEROGATORY       SafetyRatingCategory = "HARM_CATEGORY_DEROGATORY"
	SafetyRatingCategoryHARMCATEGORYTOXICITY         SafetyRatingCategory = "HARM_CATEGORY_TOXICITY"
	SafetyRatingCategoryHARMCATEGORYVIOLENCE         SafetyRatingCategory = "HARM_CATEGORY_VIOLENCE"
	SafetyRatingCategoryHARMCATEGORYSEXUAL           SafetyRatingCategory = "HARM_CATEGORY_SEXUAL"
	SafetyRatingCategoryHARMCATEGORYMEDICAL          SafetyRatingCategory = "HARM_CATEGORY_MEDICAL"
	SafetyRatingCategoryHARMCATEGORYDANGEROUS        SafetyRatingCategory = "HARM_CATEGORY_DANGEROUS"
	SafetyRatingCategoryHARMCATEGORYHARASSMENT       SafetyRatingCategory = "HARM_CATEGORY_HARASSMENT"
	SafetyRatingCategoryHARMCATEGORYHATESPEECH       SafetyRatingCategory = "HARM_CATEGORY_HATE_SPEECH"
	SafetyRatingCategoryHARMCATEGORYSEXUALLYEXPLICIT SafetyRatingCategory = "HARM_CATEGORY_SEXUALLY_EXPLICIT"
	SafetyRatingCategoryHARMCATEGORYDANGEROUSCONTENT SafetyRatingCategory = "HARM_CATEGORY_DANGEROUS_CONTENT"
	SafetyRatingCategoryHARMCATEGORYCIVICINTEGRITY   SafetyRatingCategory = "HARM_CATEGORY_CIVIC_INTEGRITY"
	SafetyRatingCategoryHARMCATEGORYJAILBREAK        SafetyRatingCategory = "HARM_CATEGORY_JAILBREAK"
)

// Logprobs Result
type LogprobsResult struct {
	// Sum of log probabilities for all tokens.
	LogProbabilitySum *float64 `json:"logProbabilitySum,omitempty"`
	// Length = total number of decoding steps.
	TopCandidates []TopCandidates `json:"topCandidates,omitempty"`
	// Length = total number of decoding steps. The chosen candidates may or may not be in top_candidates.
	ChosenCandidates []LogprobsResultCandidate `json:"chosenCandidates,omitempty"`
}

// Attribution for a source that contributed to an answer.
type GroundingAttribution struct {
	// Output only. Identifier for the source contributing to this attribution.
	SourceId *AttributionSourceId `json:"sourceId,omitempty"`
	// Grounding source content that makes up this attribution.
	Content *Content `json:"content,omitempty"`
}

// Metadata related to url context retrieval tool.
type UrlContextMetadata struct {
	// List of url context.
	UrlMetadata []UrlMetadata `json:"urlMetadata,omitempty"`
}

// A collection of source attributions for a piece of content.
type CitationMetadata struct {
	// Citations to sources for a specific response.
	CitationSources []CitationSource `json:"citationSources,omitempty"`
}

// Metadata returned to client when grounding is enabled.
type GroundingMetadata struct {
	// List of grounding support.
	GroundingSupports []GoogleAiGenerativelanguageV1BetaGroundingSupport `json:"groundingSupports,omitempty"`
	// Optional. Google search entry for the following-up web searches.
	SearchEntryPoint *SearchEntryPoint `json:"searchEntryPoint,omitempty"`
	// List of supporting references retrieved from specified grounding source. When streaming, this only contains the grounding chunks that have not been included in the grounding metadata of previous responses.
	GroundingChunks []GroundingChunk `json:"groundingChunks,omitempty"`
	// Metadata related to retrieval in the grounding flow.
	RetrievalMetadata *RetrievalMetadata `json:"retrievalMetadata,omitempty"`
	// Optional. Resource name of the Google Maps widget context token that can be used with the PlacesContextElement widget in order to render contextual data. Only populated in the case that grounding with Google Maps is enabled.
	GoogleMapsWidgetContextToken *string `json:"googleMapsWidgetContextToken,omitempty"`
	// Web search queries for the following-up web search.
	WebSearchQueries []string `json:"webSearchQueries,omitempty"`
	// Image search queries used for grounding.
	ImageSearchQueries []string `json:"imageSearchQueries,omitempty"`
}

// Represents token counting info for a single modality.
type ModalityTokenCount struct {
	// The modality associated with this token count.
	Modality *ModalityTokenCountModality `json:"modality,omitempty"`
	// Number of tokens.
	TokenCount *int `json:"tokenCount,omitempty"`
}

// The modality associated with this token count.
type ModalityTokenCountModality string

const (
	ModalityTokenCountModalityMODALITYUNSPECIFIED ModalityTokenCountModality = "MODALITY_UNSPECIFIED"
	ModalityTokenCountModalityTEXT                ModalityTokenCountModality = "TEXT"
	ModalityTokenCountModalityIMAGE               ModalityTokenCountModality = "IMAGE"
	ModalityTokenCountModalityVIDEO               ModalityTokenCountModality = "VIDEO"
	ModalityTokenCountModalityAUDIO               ModalityTokenCountModality = "AUDIO"
	ModalityTokenCountModalityDOCUMENT            ModalityTokenCountModality = "DOCUMENT"
)

// An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
type LatLng struct {
	// The longitude in degrees. It must be in the range [-180.0, +180.0].
	Longitude *float64 `json:"longitude,omitempty"`
	// The latitude in degrees. It must be in the range [-90.0, +90.0].
	Latitude *float64 `json:"latitude,omitempty"`
}

// Configuration for audio output format.
type AudioResponseFormat struct {
	// Optional. The MIME type of the audio output.
	MimeType *AudioResponseFormatMimeType `json:"mimeType,omitempty"`
	// Optional. The delivery mode for the audio output.
	Delivery *AudioResponseFormatDelivery `json:"delivery,omitempty"`
	// Optional. Bit rate in bits per second (bps). Only applicable for compressed formats (MP3, Opus).
	BitRate *int `json:"bitRate,omitempty"`
	// Optional. Sample rate in Hz.
	SampleRate *int `json:"sampleRate,omitempty"`
}

// Optional. The MIME type of the audio output.
type AudioResponseFormatMimeType string

const (
	AudioResponseFormatMimeTypeMIMETYPEUNSPECIFIED AudioResponseFormatMimeType = "MIME_TYPE_UNSPECIFIED"
	AudioResponseFormatMimeTypeAUDIOMP3            AudioResponseFormatMimeType = "AUDIO_MP3"
	AudioResponseFormatMimeTypeAUDIOOGGOPUS        AudioResponseFormatMimeType = "AUDIO_OGG_OPUS"
	AudioResponseFormatMimeTypeAUDIOL16            AudioResponseFormatMimeType = "AUDIO_L16"
	AudioResponseFormatMimeTypeAUDIOWAV            AudioResponseFormatMimeType = "AUDIO_WAV"
	AudioResponseFormatMimeTypeAUDIOALAW           AudioResponseFormatMimeType = "AUDIO_ALAW"
	AudioResponseFormatMimeTypeAUDIOMULAW          AudioResponseFormatMimeType = "AUDIO_MULAW"
)

// Optional. The delivery mode for the audio output.
type AudioResponseFormatDelivery string

const (
	AudioResponseFormatDeliveryDELIVERYUNSPECIFIED AudioResponseFormatDelivery = "DELIVERY_UNSPECIFIED"
	AudioResponseFormatDeliveryINLINE              AudioResponseFormatDelivery = "INLINE"
	AudioResponseFormatDeliveryURI                 AudioResponseFormatDelivery = "URI"
)

// Configuration for text output format.
type TextResponseFormat struct {
	// Optional. The MIME type of the text output.
	MimeType *TextResponseFormatMimeType `json:"mimeType,omitempty"`
	// Optional. The JSON schema that the output should conform to. Only applicable when mime_type is APPLICATION_JSON.
	Schema any `json:"schema,omitempty"`
}

// Optional. The MIME type of the text output.
type TextResponseFormatMimeType string

const (
	TextResponseFormatMimeTypeMIMETYPEUNSPECIFIED TextResponseFormatMimeType = "MIME_TYPE_UNSPECIFIED"
	TextResponseFormatMimeTypeAPPLICATIONJSON     TextResponseFormatMimeType = "APPLICATION_JSON"
	TextResponseFormatMimeTypeTEXTPLAIN           TextResponseFormatMimeType = "TEXT_PLAIN"
)

// Configuration for image output format.
type ImageResponseFormat struct {
	// Optional. The MIME type of the image output.
	MimeType *ImageResponseFormatMimeType `json:"mimeType,omitempty"`
	// Optional. The delivery mode for the image output.
	Delivery *ImageResponseFormatDelivery `json:"delivery,omitempty"`
	// Optional. The aspect ratio for the image output.
	AspectRatio *ImageResponseFormatAspectRatio `json:"aspectRatio,omitempty"`
	// Optional. The size of the image output.
	ImageSize *ImageResponseFormatImageSize `json:"imageSize,omitempty"`
}

// Optional. The MIME type of the image output.
type ImageResponseFormatMimeType string

const (
	ImageResponseFormatMimeTypeMIMETYPEUNSPECIFIED ImageResponseFormatMimeType = "MIME_TYPE_UNSPECIFIED"
	ImageResponseFormatMimeTypeIMAGEJPEG           ImageResponseFormatMimeType = "IMAGE_JPEG"
)

// Optional. The delivery mode for the image output.
type ImageResponseFormatDelivery string

const (
	ImageResponseFormatDeliveryDELIVERYUNSPECIFIED ImageResponseFormatDelivery = "DELIVERY_UNSPECIFIED"
	ImageResponseFormatDeliveryINLINE              ImageResponseFormatDelivery = "INLINE"
	ImageResponseFormatDeliveryURI                 ImageResponseFormatDelivery = "URI"
)

// Optional. The aspect ratio for the image output.
type ImageResponseFormatAspectRatio string

const (
	ImageResponseFormatAspectRatioASPECTRATIOUNSPECIFIED     ImageResponseFormatAspectRatio = "ASPECT_RATIO_UNSPECIFIED"
	ImageResponseFormatAspectRatioASPECTRATIOONEBYONE        ImageResponseFormatAspectRatio = "ASPECT_RATIO_ONE_BY_ONE"
	ImageResponseFormatAspectRatioASPECTRATIOTWOBYTHREE      ImageResponseFormatAspectRatio = "ASPECT_RATIO_TWO_BY_THREE"
	ImageResponseFormatAspectRatioASPECTRATIOTHREEBYTWO      ImageResponseFormatAspectRatio = "ASPECT_RATIO_THREE_BY_TWO"
	ImageResponseFormatAspectRatioASPECTRATIOTHREEBYFOUR     ImageResponseFormatAspectRatio = "ASPECT_RATIO_THREE_BY_FOUR"
	ImageResponseFormatAspectRatioASPECTRATIOFOURBYTHREE     ImageResponseFormatAspectRatio = "ASPECT_RATIO_FOUR_BY_THREE"
	ImageResponseFormatAspectRatioASPECTRATIOFOURBYFIVE      ImageResponseFormatAspectRatio = "ASPECT_RATIO_FOUR_BY_FIVE"
	ImageResponseFormatAspectRatioASPECTRATIOFIVEBYFOUR      ImageResponseFormatAspectRatio = "ASPECT_RATIO_FIVE_BY_FOUR"
	ImageResponseFormatAspectRatioASPECTRATIONINEBYSIXTEEN   ImageResponseFormatAspectRatio = "ASPECT_RATIO_NINE_BY_SIXTEEN"
	ImageResponseFormatAspectRatioASPECTRATIOSIXTEENBYNINE   ImageResponseFormatAspectRatio = "ASPECT_RATIO_SIXTEEN_BY_NINE"
	ImageResponseFormatAspectRatioASPECTRATIOTWENTYONEBYNINE ImageResponseFormatAspectRatio = "ASPECT_RATIO_TWENTY_ONE_BY_NINE"
	ImageResponseFormatAspectRatioASPECTRATIOONEBYEIGHT      ImageResponseFormatAspectRatio = "ASPECT_RATIO_ONE_BY_EIGHT"
	ImageResponseFormatAspectRatioASPECTRATIOEIGHTBYONE      ImageResponseFormatAspectRatio = "ASPECT_RATIO_EIGHT_BY_ONE"
	ImageResponseFormatAspectRatioASPECTRATIOONEBYFOUR       ImageResponseFormatAspectRatio = "ASPECT_RATIO_ONE_BY_FOUR"
	ImageResponseFormatAspectRatioASPECTRATIOFOURBYONE       ImageResponseFormatAspectRatio = "ASPECT_RATIO_FOUR_BY_ONE"
)

// Optional. The size of the image output.
type ImageResponseFormatImageSize string

const (
	ImageResponseFormatImageSizeIMAGESIZEUNSPECIFIED ImageResponseFormatImageSize = "IMAGE_SIZE_UNSPECIFIED"
	ImageResponseFormatImageSizeIMAGESIZEFIVETWELVE  ImageResponseFormatImageSize = "IMAGE_SIZE_FIVE_TWELVE"
	ImageResponseFormatImageSizeIMAGESIZEONEK        ImageResponseFormatImageSize = "IMAGE_SIZE_ONE_K"
	ImageResponseFormatImageSizeIMAGESIZETWOK        ImageResponseFormatImageSize = "IMAGE_SIZE_TWO_K"
	ImageResponseFormatImageSizeIMAGESIZEFOURK       ImageResponseFormatImageSize = "IMAGE_SIZE_FOUR_K"
)

// The configuration for the multi-speaker setup.
type MultiSpeakerVoiceConfig struct {
	// Required. All the enabled speaker voices.
	SpeakerVoiceConfigs []SpeakerVoiceConfig `json:"speakerVoiceConfigs,omitempty"`
}

// The configuration for the voice to use.
type VoiceConfig struct {
	// The configuration for the prebuilt voice to use.
	PrebuiltVoiceConfig *PrebuiltVoiceConfig `json:"prebuiltVoiceConfig,omitempty"`
}

// Deprecated: Use `GenerateContentRequest.processing_options` instead. Metadata describes the input video content.
type VideoMetadata struct {
	// Optional. The start offset of the video.
	StartOffset *string `json:"startOffset,omitempty"`
	// Optional. The end offset of the video.
	EndOffset *string `json:"endOffset,omitempty"`
	// Optional. The frame rate of the video sent to the model. If not specified, the default value will be 1.0. The fps range is (0.0, 24.0].
	Fps *float64 `json:"fps,omitempty"`
}

// Code generated by the model that is meant to be executed, and the result returned to the model. Only generated when using the `CodeExecution` tool, in which the code will be automatically executed, and a corresponding `CodeExecutionResult` will also be generated.
type ExecutableCode struct {
	// Required. The code to be executed.
	Code *string `json:"code,omitempty"`
	// Optional. Unique identifier of the `ExecutableCode` part. The server returns the `CodeExecutionResult` with the matching `id`.
	Id *string `json:"id,omitempty"`
	// Required. Programming language of the `code`.
	Language *ExecutableCodeLanguage `json:"language,omitempty"`
}

// Required. Programming language of the `code`.
type ExecutableCodeLanguage string

const (
	ExecutableCodeLanguageLANGUAGEUNSPECIFIED ExecutableCodeLanguage = "LANGUAGE_UNSPECIFIED"
	ExecutableCodeLanguagePYTHON              ExecutableCodeLanguage = "PYTHON"
)

// Result of executing the `ExecutableCode`. Generated only when the `CodeExecution` tool is used.
type CodeExecutionResult struct {
	// Optional. The identifier of the `ExecutableCode` part this result is for. Only populated if the corresponding `ExecutableCode` has an id.
	Id *string `json:"id,omitempty"`
	// Required. Outcome of the code execution.
	Outcome *CodeExecutionResultOutcome `json:"outcome,omitempty"`
	// Optional. Contains stdout when code execution is successful, stderr or other description otherwise.
	Output *string `json:"output,omitempty"`
}

// Required. Outcome of the code execution.
type CodeExecutionResultOutcome string

const (
	CodeExecutionResultOutcomeOUTCOMEUNSPECIFIED      CodeExecutionResultOutcome = "OUTCOME_UNSPECIFIED"
	CodeExecutionResultOutcomeOUTCOMEOK               CodeExecutionResultOutcome = "OUTCOME_OK"
	CodeExecutionResultOutcomeOUTCOMEFAILED           CodeExecutionResultOutcome = "OUTCOME_FAILED"
	CodeExecutionResultOutcomeOUTCOMEDEADLINEEXCEEDED CodeExecutionResultOutcome = "OUTCOME_DEADLINE_EXCEEDED"
)

type MediaResolution any

// A predicted `FunctionCall` returned from the model that contains a string representing the `FunctionDeclaration.name` with the arguments and their values.
type FunctionCall struct {
	// Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.
	Name *string `json:"name,omitempty"`
	// Optional. Unique identifier of the function call. If populated, the client to execute the `function_call` and return the response with the matching `id`.
	Id *string `json:"id,omitempty"`
	// Optional. The function parameters and values in JSON object format.
	Args map[string]any `json:"args,omitempty"`
}

// A predicted server-side `ToolCall` returned from the model. This message contains information about a tool that the model wants to invoke. The client is NOT expected to execute this `ToolCall`. Instead, the client should pass this `ToolCall` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolResponse`.
type ToolCall struct {
	// Required. The type of tool that was called.
	ToolType *ToolCallToolType `json:"toolType,omitempty"`
	// Optional. Unique identifier of the tool call. The server returns the tool response with the matching `id`.
	Id *string `json:"id,omitempty"`
	// Optional. The tool call arguments. Example: {"arg1" : "value1", "arg2" : "value2" , ...}
	Args map[string]any `json:"args,omitempty"`
}

// Required. The type of tool that was called.
type ToolCallToolType string

const (
	ToolCallToolTypeTOOLTYPEUNSPECIFIED ToolCallToolType = "TOOL_TYPE_UNSPECIFIED"
	ToolCallToolTypeGOOGLESEARCHWEB     ToolCallToolType = "GOOGLE_SEARCH_WEB"
	ToolCallToolTypeGOOGLESEARCHIMAGE   ToolCallToolType = "GOOGLE_SEARCH_IMAGE"
	ToolCallToolTypeURLCONTEXT          ToolCallToolType = "URL_CONTEXT"
	ToolCallToolTypeGOOGLEMAPS          ToolCallToolType = "GOOGLE_MAPS"
	ToolCallToolTypeFILESEARCH          ToolCallToolType = "FILE_SEARCH"
)

// The output from a server-side `ToolCall` execution. This message contains the results of a tool invocation that was initiated by a `ToolCall` from the model. The client should pass this `ToolResponse` back to the API in a subsequent turn within a `Content` message, along with the corresponding `ToolCall`.
type ToolResponse struct {
	// Optional. The tool response.
	Response map[string]any `json:"response,omitempty"`
	// Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.
	ToolType *ToolResponseToolType `json:"toolType,omitempty"`
	// Optional. The identifier of the tool call this response is for.
	Id *string `json:"id,omitempty"`
}

// Required. The type of tool that was called, matching the `tool_type` in the corresponding `ToolCall`.
type ToolResponseToolType string

const (
	ToolResponseToolTypeTOOLTYPEUNSPECIFIED ToolResponseToolType = "TOOL_TYPE_UNSPECIFIED"
	ToolResponseToolTypeGOOGLESEARCHWEB     ToolResponseToolType = "GOOGLE_SEARCH_WEB"
	ToolResponseToolTypeGOOGLESEARCHIMAGE   ToolResponseToolType = "GOOGLE_SEARCH_IMAGE"
	ToolResponseToolTypeURLCONTEXT          ToolResponseToolType = "URL_CONTEXT"
	ToolResponseToolTypeGOOGLEMAPS          ToolResponseToolType = "GOOGLE_MAPS"
	ToolResponseToolTypeFILESEARCH          ToolResponseToolType = "FILE_SEARCH"
)

// URI based data.
type FileData struct {
	// Optional. The IANA standard MIME type of the source data.
	MimeType *string `json:"mimeType,omitempty"`
	// Required. URI.
	FileUri *string `json:"fileUri,omitempty"`
}

// Raw media bytes. Text should not be sent as raw bytes, use the 'text' field.
type Blob struct {
	// The IANA standard MIME type of the source data. Examples of supported types: - Images: image/png, image/jpeg, image/jpg, image/webp, image/heic, image/heif, image/gif, image/avif - Audio: audio/*, video/audio/s16le, video/audio/wav - Video: video/* - Text: text/plain, text/html, text/css, text/javascript, text/x-typescript, text/csv, text/markdown, text/x-python, text/xml, text/rtf, video/text/timestamp - Applications: application/x-javascript, application/x-typescript, application/x-python-code, application/json, application/x-ipynb+json, application/rtf, application/pdf For additional context, see [Supported file formats](https://ai.google.dev/gemini-api/docs/file-input-methods#supported-content-types). //
	MimeType *string `json:"mimeType,omitempty"`
	// Raw bytes for media formats.
	Data *string `json:"data,omitempty"`
}

// The result output from a `FunctionCall` that contains a string representing the `FunctionDeclaration.name` and a structured JSON object containing any output from the function is used as context to the model. This should contain the result of a`FunctionCall` made based on model prediction.
type FunctionResponse struct {
	// Optional. The identifier of the function call this response is for. Populated by the client to match the corresponding function call `id`.
	Id *string `json:"id,omitempty"`
	// Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.
	Scheduling *FunctionResponseScheduling `json:"scheduling,omitempty"`
	// Required. The name of the function to call. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 128.
	Name *string `json:"name,omitempty"`
	// Optional. Ordered `Parts` that constitute a function response. Parts may have different IANA MIME types.
	Parts []FunctionResponsePart `json:"parts,omitempty"`
	// Optional. Signals that function call continues, and more responses will be returned, turning the function call into a generator. Is only applicable to NON_BLOCKING function calls, is ignored otherwise. If set to false, future responses will not be considered. It is allowed to return empty `response` with `will_continue=False` to signal that the function call is finished. This may still trigger the model generation. To avoid triggering the generation and finish the function call, additionally set `scheduling` to `SILENT`.
	WillContinue *bool `json:"willContinue,omitempty"`
	// Required. The function response in JSON object format. Callers can use any keys of their choice that fit the function's syntax to return the function output, e.g. "output", "result", etc. In particular, if the function call failed to execute, the response can have an "error" key to return error details to the model. Multimedia can be included by using a subobject containing a single "$ref" key whose value is the `inline_data.display_name` of a `FunctionResponsePart` holding the multimedia. See https://ai.google.dev/gemini-api/docs/function-calling#multimodal.
	Response map[string]any `json:"response,omitempty"`
}

// Optional. Specifies how the response should be scheduled in the conversation. Only applicable to NON_BLOCKING function calls, is ignored otherwise. Defaults to WHEN_IDLE.
type FunctionResponseScheduling string

const (
	FunctionResponseSchedulingSCHEDULINGUNSPECIFIED FunctionResponseScheduling = "SCHEDULING_UNSPECIFIED"
	FunctionResponseSchedulingSILENT                FunctionResponseScheduling = "SILENT"
	FunctionResponseSchedulingWHENIDLE              FunctionResponseScheduling = "WHEN_IDLE"
	FunctionResponseSchedulingINTERRUPT             FunctionResponseScheduling = "INTERRUPT"
)

// Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive). The start must be less than or equal to the end. When the start equals the end, the interval is empty (matches no time). When both start and end are unspecified, the interval matches any time.
type Interval struct {
	// Optional. Inclusive start of the interval. If specified, a Timestamp matching this interval will have to be the same or after the start.
	StartTime *string `json:"startTime,omitempty"`
	// Optional. Exclusive end of the interval. If specified, a Timestamp matching this interval will have to be before the end.
	EndTime *string `json:"endTime,omitempty"`
}

// Different types of search that can be enabled on the GoogleSearch tool.
type SearchTypes struct {
	// Optional. Enables image search. Image bytes are returned.
	ImageSearch *ImageSearch `json:"imageSearch,omitempty"`
	// Optional. Enables web search. Only text results are returned.
	WebSearch *WebSearch `json:"webSearch,omitempty"`
}

// Describes the options to customize dynamic retrieval.
type DynamicRetrievalConfig struct {
	// The mode of the predictor to be used in dynamic retrieval.
	Mode *DynamicRetrievalConfigMode `json:"mode,omitempty"`
	// The threshold to be used in dynamic retrieval. If not set, a system default value is used.
	DynamicThreshold *float64 `json:"dynamicThreshold,omitempty"`
}

// The mode of the predictor to be used in dynamic retrieval.
type DynamicRetrievalConfigMode string

const (
	DynamicRetrievalConfigModeMODEUNSPECIFIED DynamicRetrievalConfigMode = "MODE_UNSPECIFIED"
	DynamicRetrievalConfigModeMODEDYNAMIC     DynamicRetrievalConfigMode = "MODE_DYNAMIC"
)

// A transport that can stream HTTP requests and responses. Next ID: 6
type StreamableHttpTransport struct {
	// Optional: Fields for authentication headers, timeouts, etc., if needed.
	Headers map[string]string `json:"headers,omitempty"`
	// Timeout for SSE read operations.
	SseReadTimeout *string `json:"sseReadTimeout,omitempty"`
	// Whether to close the client session when the transport closes.
	TerminateOnClose *bool `json:"terminateOnClose,omitempty"`
	// HTTP timeout for regular operations.
	Timeout *string `json:"timeout,omitempty"`
	// The full URL for the MCPServer endpoint. Example: "https://api.example.com/mcp"
	Url *string `json:"url,omitempty"`
}

// Candidates with top log probabilities at each decoding step.
type TopCandidates struct {
	// Sorted by log probability in descending order.
	Candidates []LogprobsResultCandidate `json:"candidates,omitempty"`
}

// Candidate for the logprobs token and score.
type LogprobsResultCandidate struct {
	// The candidate’s token string value.
	Token *string `json:"token,omitempty"`
	// The candidate’s token id value.
	TokenId *int `json:"tokenId,omitempty"`
	// The candidate's log probability.
	LogProbability *float64 `json:"logProbability,omitempty"`
}

// Identifier for the source contributing to this attribution.
type AttributionSourceId struct {
	// Identifier for an inline passage.
	GroundingPassage *GroundingPassageId `json:"groundingPassage,omitempty"`
	// Identifier for a `Chunk` fetched via Semantic Retriever.
	SemanticRetrieverChunk *SemanticRetrieverChunk `json:"semanticRetrieverChunk,omitempty"`
}

// Context of the a single url retrieval.
type UrlMetadata struct {
	// Status of the url retrieval.
	UrlRetrievalStatus *UrlMetadataUrlRetrievalStatus `json:"urlRetrievalStatus,omitempty"`
	// Retrieved url by the tool.
	RetrievedUrl *string `json:"retrievedUrl,omitempty"`
}

// Status of the url retrieval.
type UrlMetadataUrlRetrievalStatus string

const (
	UrlMetadataUrlRetrievalStatusURLRETRIEVALSTATUSUNSPECIFIED UrlMetadataUrlRetrievalStatus = "URL_RETRIEVAL_STATUS_UNSPECIFIED"
	UrlMetadataUrlRetrievalStatusURLRETRIEVALSTATUSSUCCESS     UrlMetadataUrlRetrievalStatus = "URL_RETRIEVAL_STATUS_SUCCESS"
	UrlMetadataUrlRetrievalStatusURLRETRIEVALSTATUSERROR       UrlMetadataUrlRetrievalStatus = "URL_RETRIEVAL_STATUS_ERROR"
	UrlMetadataUrlRetrievalStatusURLRETRIEVALSTATUSPAYWALL     UrlMetadataUrlRetrievalStatus = "URL_RETRIEVAL_STATUS_PAYWALL"
	UrlMetadataUrlRetrievalStatusURLRETRIEVALSTATUSUNSAFE      UrlMetadataUrlRetrievalStatus = "URL_RETRIEVAL_STATUS_UNSAFE"
)

// A citation to a source for a portion of a specific response.
type CitationSource struct {
	// Optional. End of the attributed segment, exclusive.
	EndIndex *int `json:"endIndex,omitempty"`
	// Optional. License for the GitHub project that is attributed as a source for segment. License info is required for code citations.
	License *string `json:"license,omitempty"`
	// Optional. URI that is attributed as a source for a portion of the text.
	Uri *string `json:"uri,omitempty"`
	// Optional. Start of segment of the response that is attributed to this source. Index indicates the start of the segment, measured in bytes.
	StartIndex *int `json:"startIndex,omitempty"`
}

// Grounding support.
type GoogleAiGenerativelanguageV1BetaGroundingSupport struct {
	// Optional. A list of indices (into 'grounding_chunk' in `response.candidate.grounding_metadata`) specifying the citations associated with the claim. For instance [1,3,4] means that grounding_chunk[1], grounding_chunk[3], grounding_chunk[4] are the retrieved content attributed to the claim. If the response is streaming, the grounding_chunk_indices refer to the indices across all responses. It is the client's responsibility to accumulate the grounding chunks from all responses (while maintaining the same order).
	GroundingChunkIndices []int `json:"groundingChunkIndices,omitempty"`
	// Segment of the content this support belongs to.
	Segment *GoogleAiGenerativelanguageV1BetaSegment `json:"segment,omitempty"`
	// Output only. Indices into the `parts` field of the candidate's content. These indices specify which rendered parts are associated with this support source.
	RenderedParts []int `json:"renderedParts,omitempty"`
	// Optional. Confidence score of the support references. Ranges from 0 to 1. 1 is the most confident. This list must have the same size as the grounding_chunk_indices.
	ConfidenceScores []float64 `json:"confidenceScores,omitempty"`
}

// Google search entry point.
type SearchEntryPoint struct {
	// Optional. Web content snippet that can be embedded in a web page or an app webview.
	RenderedContent *string `json:"renderedContent,omitempty"`
	// Optional. Base64 encoded JSON representing array of tuple.
	SdkBlob *string `json:"sdkBlob,omitempty"`
}

// A `GroundingChunk` represents a segment of supporting evidence that grounds the model's response. It can be a chunk from the web, a retrieved context from a file, or information from Google Maps.
type GroundingChunk struct {
	// Optional. Grounding chunk from image search.
	Image *Image `json:"image,omitempty"`
	// Optional. Grounding chunk from context retrieved by the file search tool.
	RetrievedContext *RetrievedContext `json:"retrievedContext,omitempty"`
	// Grounding chunk from the web.
	Web *Web `json:"web,omitempty"`
	// Optional. Grounding chunk from Google Maps.
	Maps *Maps `json:"maps,omitempty"`
}

// Metadata related to retrieval in the grounding flow.
type RetrievalMetadata struct {
	// Optional. Score indicating how likely information from google search could help answer the prompt. The score is in the range [0, 1], where 0 is the least likely and 1 is the most likely. This score is only populated when google search grounding and dynamic retrieval is enabled. It will be compared to the threshold to determine whether to trigger google search.
	GoogleSearchDynamicRetrievalScore *float64 `json:"googleSearchDynamicRetrievalScore,omitempty"`
}

// The configuration for a single speaker in a multi speaker setup.
type SpeakerVoiceConfig struct {
	// Required. The configuration for the voice to use.
	VoiceConfig *VoiceConfig `json:"voiceConfig,omitempty"`
	// Required. The name of the speaker to use. Should be the same as in the prompt.
	Speaker *string `json:"speaker,omitempty"`
}

// The configuration for the prebuilt speaker to use.
type PrebuiltVoiceConfig struct {
	// The name of the preset voice to use.
	VoiceName *string `json:"voiceName,omitempty"`
}

// A datatype containing media that is part of a `FunctionResponse` message. A `FunctionResponsePart` consists of data which has an associated datatype. A `FunctionResponsePart` can only contain one of the accepted types in `FunctionResponsePart.data`. A `FunctionResponsePart` must have a fixed IANA MIME type identifying the type and subtype of the media if the `inline_data` field is filled with raw bytes.
type FunctionResponsePart struct {
	// Inline media bytes.
	InlineData *FunctionResponseBlob `json:"inlineData,omitempty"`
}

// Image search for grounding and related configurations.
type ImageSearch any

// Standard web search for grounding and related configurations.
type WebSearch any

// Identifier for a part within a `GroundingPassage`.
type GroundingPassageId struct {
	// Output only. ID of the passage matching the `GenerateAnswerRequest`'s `GroundingPassage.id`.
	PassageId *string `json:"passageId,omitempty"`
	// Output only. Index of the part within the `GenerateAnswerRequest`'s `GroundingPassage.content`.
	PartIndex *int `json:"partIndex,omitempty"`
}

// Identifier for a `Chunk` retrieved via Semantic Retriever specified in the `GenerateAnswerRequest` using `SemanticRetrieverConfig`.
type SemanticRetrieverChunk struct {
	// Output only. Name of the source matching the request's `SemanticRetrieverConfig.source`. Example: `corpora/123` or `corpora/123/documents/abc`
	Source *string `json:"source,omitempty"`
	// Output only. Name of the `Chunk` containing the attributed text. Example: `corpora/123/documents/abc/chunks/xyz`
	Chunk *string `json:"chunk,omitempty"`
}

// Segment of the content.
type GoogleAiGenerativelanguageV1BetaSegment struct {
	// The index of a Part object within its parent Content object.
	PartIndex *int `json:"partIndex,omitempty"`
	// Start index in the given Part, measured in bytes. Offset from the start of the Part, inclusive, starting at zero.
	StartIndex *int `json:"startIndex,omitempty"`
	// The text corresponding to the segment from the response.
	Text *string `json:"text,omitempty"`
	// End index in the given Part, measured in bytes. Offset from the start of the Part, exclusive, starting at zero.
	EndIndex *int `json:"endIndex,omitempty"`
}

// Chunk from image search.
type Image struct {
	// The title of the web page that the image is from.
	Title *string `json:"title,omitempty"`
	// The image asset URL.
	ImageUri *string `json:"imageUri,omitempty"`
	// The web page URI for attribution.
	SourceUri *string `json:"sourceUri,omitempty"`
	// The root domain of the web page that the image is from, e.g. "example.com".
	Domain *string `json:"domain,omitempty"`
}

// Chunk from context retrieved by the file search tool.
type RetrievedContext struct {
	// Optional. Name of the `FileSearchStore` containing the document. Example: `fileSearchStores/123`
	FileSearchStore *string `json:"fileSearchStore,omitempty"`
	// Optional. Text of the chunk.
	Text *string `json:"text,omitempty"`
	// Optional. Page number of the retrieved context, if applicable.
	PageNumber *int `json:"pageNumber,omitempty"`
	// Optional. URI reference of the semantic retrieval document.
	Uri *string `json:"uri,omitempty"`
	// Optional. Title of the document.
	Title *string `json:"title,omitempty"`
	// Optional. The media blob resource name for multimodal file search results. Format: fileSearchStores/{file_search_store_id}/media/{blob_id}
	MediaId *string `json:"mediaId,omitempty"`
	// Optional. User-provided metadata about the retrieved context.
	CustomMetadata []GroundingChunkCustomMetadata `json:"customMetadata,omitempty"`
}

// Chunk from the web.
type Web struct {
	// Output only. URI reference of the chunk.
	Uri *string `json:"uri,omitempty"`
	// Output only. Title of the chunk.
	Title *string `json:"title,omitempty"`
}

// A grounding chunk from Google Maps. A Maps chunk corresponds to a single place.
type Maps struct {
	// Sources that provide answers about the features of a given place in Google Maps.
	PlaceAnswerSources *PlaceAnswerSources `json:"placeAnswerSources,omitempty"`
	// Text description of the place answer.
	Text *string `json:"text,omitempty"`
	// URI reference of the place.
	Uri *string `json:"uri,omitempty"`
	// Title of the place.
	Title *string `json:"title,omitempty"`
	// The ID of the place, in `places/{place_id}` format. A user can use this ID to look up that place.
	PlaceId *string `json:"placeId,omitempty"`
}

// Raw media bytes for function response. Text should not be sent as raw bytes, use the 'FunctionResponse.response' field.
type FunctionResponseBlob struct {
	// The IANA standard MIME type of the source data. Examples: - image/png - image/jpeg If an unsupported MIME type is provided, an error will be returned. For a complete list of supported types, see [Supported file formats](https://ai.google.dev/gemini-api/docs/prompting_with_media#supported_file_formats).
	MimeType *string `json:"mimeType,omitempty"`
	// Raw bytes for media formats.
	Data *string `json:"data,omitempty"`
}

// User provided metadata about the GroundingFact.
type GroundingChunkCustomMetadata struct {
	// Optional. The numeric value of the metadata. The expected range for this value depends on the specific `key` used.
	NumericValue *float64 `json:"numericValue,omitempty"`
	// Optional. A list of string values for the metadata.
	StringListValue *GroundingChunkStringList `json:"stringListValue,omitempty"`
	// The key of the metadata.
	Key *string `json:"key,omitempty"`
	// Optional. The string value of the metadata.
	StringValue *string `json:"stringValue,omitempty"`
}

// Collection of sources that provide answers about the features of a given place in Google Maps. Each PlaceAnswerSources message corresponds to a specific place in Google Maps. The Google Maps tool used these sources in order to answer questions about features of the place (e.g: "does Bar Foo have Wifi" or "is Foo Bar wheelchair accessible?"). Currently we only support review snippets as sources.
type PlaceAnswerSources struct {
	// Snippets of reviews that are used to generate answers about the features of a given place in Google Maps.
	ReviewSnippets []ReviewSnippet `json:"reviewSnippets,omitempty"`
}

// A list of string values.
type GroundingChunkStringList struct {
	// The string values of the list.
	Values []string `json:"values,omitempty"`
}

// Encapsulates a snippet of a user review that answers a question about the features of a specific place in Google Maps.
type ReviewSnippet struct {
	// A link that corresponds to the user review on Google Maps.
	GoogleMapsUri *string `json:"googleMapsUri,omitempty"`
	// The ID of the review snippet.
	ReviewId *string `json:"reviewId,omitempty"`
	// Title of the review.
	Title *string `json:"title,omitempty"`
}
