name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: |
            **/go.sum
            go.work.sum

      - name: Install dependencies
        run: go mod download

      - name: Vet
        run: |
          go vet ./sdk-go/...

      - name: Build
        run: |
          go build ./sdk-go/...

      # - name: Test
      #   run: go test -v ./...
