name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - name: Install native dependencies
        run: sudo apt-get install -y libasound2-dev

      - name: Run Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy
      - name: Run Formatter
        run: cargo +nightly fmt -- --check
      - name: Build
        run: cargo build

      - name: Test
        run: cargo test --lib agent-sdk
