name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: RUSTFLAGS="-Dwarnings" cargo clippy
      - name: Run Formatter
        run: cargo +nightly fmt -- --check
      - name: Build
        run: cargo build
